#!/bin/sh

echo "START: $0"

for libdir in /usr/lib*
do

    [ ! -d "$libdir" ] && continue

    for x in `ls -d $libdir/*/ptest 2>/dev/null`
    do
        [ ! -f $x/run-ptest ] && continue
        [ -h `dirname $x` ] && continue

        date "+%Y-%m-%dT%H:%M"
        echo "BEGIN: $x"
        cd "$x"
        ./run-ptest
        echo "END: $x"
        date "+%Y-%m-%dT%H:%M"
    done
done
echo "STOP: $0"
