#!/bin/sh

export TCL_LIBRARY=@libdir@/tcl/ptest/library
export ERROR_ON_FAILURES=1
export LANG=en-US.UTF-8

# Some tests are overly strict with timings and fail on loaded systems.
SKIP=""
# 15321
SKIP="$SKIP async-\* event-\*"
# 14882
SKIP="$SKIP cmdMZ-6.6"
# 15081
SKIP="$SKIP exit-1.\*"
# 15407 15421
SKIP="$SKIP \*io-46.1"
# io-13.6 explicitly says it can fail on slow/loaded machines
SKIP="$SKIP \*io-13.6"
# The socket tests seem to be problematic with tight timing conditions, skip them all.
# 14825 15495
SKIP="$SKIP socket-\* socket_inet\* socket_inet6\*"
# These tests seem to be unreliable:
# https://core.tcl-lang.org/tcl/tktview/3764f4e81f1483ab554c6d60f8483887bde28221
SKIP="$SKIP http11-\*"
# tries to access google.com
SKIP="$SKIP httpProxy-\*"

for name in tests/*.test; do
    ./tcltest $name -skip "$SKIP"
    if [ $? -eq 0 ]; then
        echo "PASS: $name"
    else
        echo "FAIL: $name"
    fi
done
