#!/bin/sh

cd tests

for t in libconfig_tests; do
    if [ -x ./$t ]; then
        ./$t
        if [ $? -eq 0 ]; then
            echo "PASS: $t"
        else
            echo "FAIL: $t"
        fi
    else
        echo "SKIP: $t"
    fi
done
