#! /bin/sh
### BEGIN INIT INFO
# Provides:          umountfs
# Required-Start:
# Required-Stop:     
# Default-Start:
# Default-Stop:      0 6
# Short-Description: Turn off swap and unmount all local file systems.
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo "Deactivating swap..."
swapoff -a

# We leave /proc mounted.
echo "Unmounting local filesystems..."
mount -o remount,ro /mnt/ram
umount -f -a -r

mount -o remount,ro /

: exit 0
