#!/bin/sh

export GDK_PIXBUF_MODULEDIR=$D${libdir}/gdk-pixbuf-2.0/2.10.0/loaders

PSEUDO_UNLOAD=1 qemuwrapper -L $D -E LD_LIBRARY_PATH=$D/${libdir}:$D/${base_libdir}\
    $D${bindir}/gdk-pixbuf-query-loaders \
    >$GDK_PIXBUF_MODULEDIR/../loaders.cache 2>/dev/null && \
    sed -i -e "s:$D::g" $GDK_PIXBUF_MODULEDIR/../loaders.cache


