#!/bin/sh
#
# SPDX-License-Identifier: MIT
#

set -e

case "${PREFERRED_PROVIDER_udev}" in
	systemd)
		echo Updating HWDB with native systemd-hwdb...
		systemd-hwdb update --root $D --usr
		;;

	*)
		echo Updating HWDB with udevadm...

		UDEVLIBDIR="${sysconfdir}"
		UDEVADM="${bindir}/udevadm"

		rm -f $D${UDEVLIBDIR}/udev/hwdb.bin
		PSEUDO_UNLOAD=1 ${binprefix}qemuwrapper -L $D $D${UDEVADM} hwdb --update --root $D ||
			PSEUDO_UNLOAD=1 qemuwrapper -L $D $D${UDEVADM} hwdb --update --root $D
		chown root:root $D${UDEVLIBDIR}/udev/hwdb.bin
		;;
esac
