#!/bin/bash
#
# Boot Test Case for Sanity Test
# The case boot up the Qemu target with `runqemu qemuxxx`.
# Then check if qemu and qemu network is up.
#
# Author: Jiajun Xu <jiajun.xu@intel.com>
#
# This file is licensed under the GNU General Public License,
# Version 2.
#
. $COREBASE/scripts/qemuimage-testlib

TIMEOUT=120

# Start qemu and check its network
Test_Create_Qemu ${TIMEOUT}

if [ $? -eq 0 ]; then
	Test_Info "Boot Test PASS"
	Test_Kill_Qemu
	Test_Print_Result "Boot" 0
	exit 0
else
	Test_Info "Boot Test FAIL"
	Test_Kill_Qemu
	Test_Print_Result "Boot" 1
	exit 1
fi
