#!/bin/bash
# Compiler Test Case for Sanity Test
# The case boot up the Qemu target with `runqemu qemuxxx`.
# Then check if gcc/g++/make command can work in target.
#
# Author: Jiajun Xu <jiajun.xu@intel.com>
#
# This file is licensed under the GNU General Public License,
# Version 2.
#

. $COREBASE/scripts/qemuimage-testlib

TIMEOUT=400
RET=1

# Start qemu and check its network
Test_Create_Qemu ${TIMEOUT}

# If qemu network is up, check ssh service in qemu
if [ $? -eq 0 ]; then
	Test_Info "Begin to Test SSH Service in Qemu"
	Test_SSH_UP ${TARGET_IPADDR} ${TIMEOUT}
	RET=$?
else
	RET=1
fi

# Check if gcc/g++/make can work in target
if [ $RET -eq 0 -a -f $TOOLS/compiler_test.sh ]; then
	# Copy compiler_test.sh into target
	Test_Target_Pre ${TARGET_IPADDR} $TOOLS/compiler_test.sh
	if [ $? -eq 0 ]; then
		# Run compiler_test.sh to check if gcc/g++/make can work in target
		Test_SSH ${TARGET_IPADDR} "sh $TARGET_TEST_DIR/compiler_test.sh"
		RET=$?
	else
		RET=1
	fi
fi

if [ ${RET} -eq 0 ]; then
	Test_Info "Compiler Test PASS"
	Test_Kill_Qemu
	Test_Print_Result "compiler" 0
	exit 0
else
	Test_Info "Compiler FAIL, Pls. check above error log"
	Test_Kill_Qemu
	Test_Print_Result "compiler" 1
	exit 1
fi
