#!/bin/bash
# SSH Test Case for Sanity Test
# The case boot up the Qemu target with `runqemu qemuxxx`.
# Then check if ssh service in qemu is up.
#
# Author: Jiajun Xu <jiajun.xu@intel.com>
#
# This file is licensed under the GNU General Public License,
# Version 2.
#

. $COREBASE/scripts/qemuimage-testlib

TIMEOUT=400
RET=1

# Start qemu and check its network
Test_Create_Qemu ${TIMEOUT}

# If qemu network is up, check ssh service in qemu
if [ $? -eq 0 ]; then
	Test_Info "Begin to Test SSH Service in Qemu"
	Test_SSH_UP ${TARGET_IPADDR} ${TIMEOUT}
	RET=$?
else
	RET=1
fi

if [ ${RET} -eq 0 ]; then
	Test_Info "SSH Test PASS"
	Test_Kill_Qemu
	Test_Print_Result "SSH" 0
	exit 0
else
	Test_Info "SSH Test FAIL"
	Test_Kill_Qemu
	Test_Print_Result "SSH" 1
	exit 1
fi
