#!/bin/sh

# Poky Build Enviroment Setup Script
#
# Copyright (C) 2006  OpenedHand LTD
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

if test x"$0" = x"./poky-init-build-env"; then
   echo "Error: Run via '. ./poky-init-build-env'"
   exit 1
fi

#
# Change this to the location of this file.
# Also update the locations at the top of conf/local.conf
#
OEROOT=`pwd`

SITEDIR=$HOME/.oe/
BBDIR=$OEROOT/bitbake/
PKGDIR=$OEROOT/meta/
BUILDDIR=$OEROOT/build/
MSG=''

PATH=$BBDIR/bin/:$PATH

cd $BUILDDIR

# Remove any symlinks from paths
SITEDIR=`readlink -f $SITEDIR`
BBDIR=`readlink -f $BBDIR`
PKGDIR=`readlink -f $PKGDIR`
BUILDDIR=`readlink -f $BUILDDIR`

if ! (test -d $BBDIR && test -d $PKGDIR && test -d $BUILDDIR); then
    echo >&2 "Error: Not all directories exist! Did you run this script in poky directory?"
    exit 1
fi

BBPATH=$BBDIR
if test x"$BBDIR" != x"$PKGDIR"; then
	BBPATH=$PKGDIR:$BBPATH
fi
if test x"$SITEDIR" != x"$SITEDIR" && test -d $SITEDIR; then
	BBPATH=$SITEDIR:$BBPATH
fi
if test x"$PKGDIR" != x"$BUILDDIR"; then
	BBPATH=$BUILDDIR:$BBPATH
fi
export BBPATH

# Kill off the TERMINFO variable, as glibc will grab its contents in its 'make
# install' if set
unset TERMINFO
# kill this so we don't link non-arm libraries
unset LD_LIBRARY_PATH
# Don't export TARGET_ARCH - it *will* cause build failures
export PATH LD_LIBRARY_PATH OEROOT
# Stop multi byte characters breaking the patcher stuff - This is for Redhat / Fedora people really
export LANG=C

echo
echo "### Shell environment set up for Poky builds. ###"
echo 
