# Overide some bits

DISTRO = "openzaurus"
DISTRO_NAME = "OpenedHand PokyLinux" # Bad?
DISTRO_VERSION = "0.0-snapshot-${DATE}"

DISTRO_TYPE = "debug"
# DISTRO_TYPE = "release"

#PREFERRED_PROVIDER_gconf=gconf-dbus

CVSDATE_ipkg-utils-native = "20050930"
CVSDATE_ipkg-link-1 = "20050930"
CVSDATE_ipkg-utils = "20050930"
CVSDATE_ipkg-link = "20050930"
CVSDATE_matchbox-common = "20051101"
CVSDATE_matchbox-config-gtk = "20051101"
CVSDATE_matchbox-desktop = "20051101"
CVSDATE_matchbox-keyboard = "20051101"
CVSDATE_matchbox-panel = "20051101"
CVSDATE_matchbox-panel-manager = "20051101"
CVSDATE_matchbox-stroke = "20051101"
CVSDATE_matchbox-themes-extra = "20051101"
CVSDATE_matchbox-wm = "20051101"
CVSDATE_libmatchbox = "20051101"
CVSDATE_tslib = "20051101"
CVSDATE_xext = "20051101"
CVSDATE_renderext = "20051101"
CVSDATE_libxrender = "20051101"
CVSDATE_fixesext = "20051101"
CVSDATE_damageext = "20051101"
CVSDATE_compositeext = "20051101"
CVSDATE_xcalibrateext = "20051101"
CVSDATE_recordext = "20051101"


#PREFERRED_VERSION_matchbox = "0.9.1"
#PREFERRED_VERSION_matchbox-applet-inputmanager = "0.6"
#PREFERRED_VERSION_matchbox-applet-startup-monitor = "0.1"
#PREFERRED_VERSION_matchbox-common = "0.9.1+cvs-${CVSDATE}"
#PREFERRED_VERSION_matchbox-config-gtk = "0.0+cvs-${CVSDATE}"
#PREFERRED_VERSION_matchbox-desktop = "0.9.1+cvs-${CVSDATE}"
#PREFERRED_VERSION_matchbox-keyboard = "0.0+cvs-${CVSDATE}"
#PREFERRED_VERSION_matchbox-panel = "0.9.2+cvs-${CVSDATE}"
#PREFERRED_VERSION_matchbox-panel-manager = "0.0+cvs-${CVSDATE}"
#PREFERRED_VERSION_matchbox-stroke = "0.0+cvs-${CVSDATE}"
#PREFERRED_VERSION_matchbox-themes-extra = "0.3+cvs-${CVSDATE}"
#PREFERRED_VERSION_matchbox-wm = "0.9.5+cvs-${CVSDATE}"
#PREFERRED_VERSION_libmatchbox = "1.7+cvs-${CVSDATE}"


PREFERRED_VERSION_atk = "1.10.0"
PREFERRED_VERSION_cairo = "1.0.0"
PREFERRED_VERSION_glib-2.0 = "2.8.1"
PREFERRED_VERSION_gtk+ = "2.6.7"
PREFERRED_VERSION_pango = "1.10.0"

PREFERRED_VERSION_dbus = "0.50"
