#
# Specify which versions of E-related libraries and applications to build
#

PREFERRED_VERSION_ecore = "0.9.9.013"
PREFERRED_VERSION_edb = "1.0.5.004"
PREFERRED_VERSION_edje = "0.5.0.013"
PREFERRED_VERSION_eet = "0.9.10.013"
PREFERRED_VERSION_embryo = "0.9.1.013"
PREFERRED_VERSION_etox = "0.9.0.004"
PREFERRED_VERSION_evas = "0.9.9.013"
PREFERRED_VERSION_ewl = "0.0.4.004"
PREFERRED_VERSION_imlib2 = "1.2.1.004"
