#
# Specify which versions of E-related libraries and applications to build
#

PREFERRED_VERSION_e = "0.16.999.023"
PREFERRED_VERSION_ecore-x11 = "0.9.9.023"
PREFERRED_VERSION_ecore-native = "0.9.9.023"
PREFERRED_VERSION_edb = "1.0.5.005"
PREFERRED_VERSION_edb-native = "1.0.5.005"
PREFERRED_VERSION_edje = "0.5.0.023"
PREFERRED_VERSION_edje-native = "0.5.0.023"
PREFERRED_VERSION_eet = "0.9.10.023"
PREFERRED_VERSION_eet-native = "0.9.10.023"
PREFERRED_VERSION_embryo = "0.9.1.023"
PREFERRED_VERSION_embryo-native = "0.9.1.023"
PREFERRED_VERSION_emotion = "0.0.1.004"
PREFERRED_VERSION_emotion-native = "0.0.1.004"
PREFERRED_VERSION_epeg = "0.9.0.005"
PREFERRED_VERSION_epsilon = "0.3.0.005"
PREFERRED_VERSION_esmart-x11 = "0.9.0.005"
PREFERRED_VERSION_evas-x11 = "0.9.9.023"
PREFERRED_VERSION_evas-native = "0.9.9.023"
PREFERRED_VERSION_ewl = "0.0.4.005"
PREFERRED_VERSION_imlib2-x11 = "1.2.1.010"
PREFERRED_VERSION_imlib2-native = "1.2.1.010"
PREFERRED_VERSION_e-wm = "0.16.999.023"
PREFERRED_VERSION_entrance = "0.9.0.005"

PREFERRED_PROVIDER_virtual/evas = "evas-x11"
PREFERRED_PROVIDER_virtual/ecore = "ecore-x11"
PREFERRED_PROVIDER_virtual/imlib2 = "imlib2-x11"

PREFERRED_VERSION_gnome-vfs-dbus = "svn"

PREFERRED_VERSION_gcc = "3.4.4"
