#!/bin/sh
set -eux

for t in config control midi_event client_event_filter
do
    if "./$t" > "alsa-lib_$t.log" 2>&1
    then
        echo "PASS: $t"
    else
        echo "FAIL: $t"
        cat "alsa-lib_$t.log"
    fi
    rm "alsa-lib_$t.log"
done
