#!/bin/sh

set -e

export LC_ALL=en_US.UTF-8

# testModule isn't that useful and hard-codes buildtree, so we don't run that
TESTS="runtest runsuite testrecurse testchar testdict runxmlconf testapi testlimits testparser"

for T in $TESTS; do
    echo Running $T
    ./$T && echo PASS: $T || echo FAIL: $T
done
