#
# distro tracking fields for X11 apps(high level)
#

RECIPE_STATUS_pn-owl-video = "green" # no update needed
DEPENDENCY_CHECK_pn-owl-video = "not done"
RECIPE_LATEST_VERSION_pn-owl-video = "394"
RECIPE_NO_OF_PATCHES_pn-owl-video = "0"
RECIPE_INTEL_SECTION_pn-owl-video = "graphic apps"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-owl-video = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-owl-video = "06/2008"
RECIPE_COMMENTS_pn-owl-video = ""
RECIPE_MAINTAINER_pn-owl-video = "Zhai Edwin <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xtscal = "green" # no update needed
DEPENDENCY_CHECK_pn-xtscal = "not done"
RECIPE_LATEST_VERSION_pn-xtscal = "0.6.3"
RECIPE_NO_OF_PATCHES_pn-xtscal = "2"
RECIPE_INTEL_SECTION_pn-xtscal = "graphic apps"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xtscal = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-xtscal = "06/2006"
RECIPE_COMMENTS_pn-xtscal = ""
RECIPE_MAINTAINER_pn-xtscal = "Zhai Edwin <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xrestop = "green" # no update needed
DEPENDENCY_CHECK_pn-xrestop = "not done"
RECIPE_LATEST_VERSION_pn-xrestop = "0.4"
RECIPE_NO_OF_PATCHES_pn-xrestop = "0"
RECIPE_INTEL_SECTION_pn-xrestop = "graphic apps"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xrestop = "18 months"
RECIPE_LATEST_RELEASE_DATE_pn-xrestop = "03/2006"
RECIPE_COMMENTS_pn-xrestop = ""
RECIPE_MAINTAINER_pn-xrestop = "Zhai Edwin <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-pcmanfm = "green"
DEPENDENCY_CHECK_pn-pcmanfm = "not done"
RECIPE_LATEST_VERSION_pn-pcmanfm = "0.9.7"
RECIPE_NO_OF_PATCHES_pn-pcmanfm = "4"
RECIPE_INTEL_SECTION_pn-pcmanfm = "graphic apps"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-pcmanfm = "4 months"
RECIPE_LATEST_RELEASE_DATE_pn-pcmanfm = "05/2010"
RECIPE_COMMENTS_pn-pcmanfm = ""
RECIPE_MAINTAINER_pn-pcmanfm = "Zhai Edwin <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-oh-puzzles = "green" # no update needed
DEPENDENCY_CHECK_pn-oh-puzzles = "not done"
RECIPE_LATEST_VERSION_pn-oh-puzzles = "0.1+svnr23"
RECIPE_NO_OF_PATCHES_pn-oh-puzzles = "1"
RECIPE_INTEL_SECTION_pn-oh-puzzles = "graphic apps"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-oh-puzzles = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-oh-puzzles = "04/2008"
RECIPE_COMMENTS_pn-oh-puzzles = ""
RECIPE_MAINTAINER_pn-oh-puzzles = "Zhai Edwin <edwin.zhai@intel.com>"


RECIPE_STATUS_pn-gnome-terminal = "red"
RECIPE_LATEST_VERSION_pn-gnome-terminal = "2.31.3"
RECIPE_MAINTAINER_pn-gnome-terminal = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-puzzles = "red"
RECIPE_LATEST_VERSION_pn-puzzles = "svn_8956"
RECIPE_MAINTAINER_pn-puzzles = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xdg-user-dirs = "red"
RECIPE_LATEST_VERSION_pn-xdg-user-dirs = "0.12"
RECIPE_MAINTAINER_pn-xdg-user-dirs = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xterm = "red"
RECIPE_LATEST_VERSION_pn-xterm = "n/a"
RECIPE_MAINTAINER_pn-xterm = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-iceauth = "red"
RECIPE_LATEST_VERSION_pn-iceauth = "1.0.3"
RECIPE_MAINTAINER_pn-iceauth = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-luit = "red"
RECIPE_LATEST_VERSION_pn-luit = "1.0.5"
RECIPE_MAINTAINER_pn-luit = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-oclock = "red"
RECIPE_LATEST_VERSION_pn-oclock = "n/a"
RECIPE_MAINTAINER_pn-oclock = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-rgb = "red"
RECIPE_LATEST_VERSION_pn-rgb = "1.0.3"
RECIPE_MAINTAINER_pn-rgb = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-x11perf = "red"
RECIPE_LATEST_VERSION_pn-x11perf = "1.5.1"
RECIPE_MAINTAINER_pn-x11perf = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xbacklight = "red"
RECIPE_LATEST_VERSION_pn-xbacklight = "1.1.1"
RECIPE_MAINTAINER_pn-xbacklight = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xbiff = "red"
RECIPE_LATEST_VERSION_pn-xbiff = "1.0.2"
RECIPE_MAINTAINER_pn-xbiff = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xclipboard = "red"
RECIPE_LATEST_VERSION_pn-xclipboard = "1.1.0"
RECIPE_MAINTAINER_pn-xclipboard = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xclock = "red"
RECIPE_LATEST_VERSION_pn-xclock = "n/a"
RECIPE_MAINTAINER_pn-xclock = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xcmsdb = "red"
RECIPE_LATEST_VERSION_pn-xcmsdb = "1.0.2"
RECIPE_MAINTAINER_pn-xcmsdb = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xconsole = "red"
RECIPE_LATEST_VERSION_pn-xconsole = "1.0.3"
RECIPE_MAINTAINER_pn-xconsole = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xcursorgen = "red"
RECIPE_LATEST_VERSION_pn-xcursorgen = "1.0.3"
RECIPE_MAINTAINER_pn-xcursorgen = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xdriinfo = "red"
RECIPE_LATEST_VERSION_pn-xdriinfo = "1.0.3"
RECIPE_MAINTAINER_pn-xdriinfo = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xev = "red"
RECIPE_LATEST_VERSION_pn-xev = "1.0.4"
RECIPE_MAINTAINER_pn-xev = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xeyes = "red"
RECIPE_LATEST_VERSION_pn-xeyes = "1.1.0"
RECIPE_MAINTAINER_pn-xeyes = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xfd = "red"
RECIPE_LATEST_VERSION_pn-xfd = "1.0.1"
RECIPE_MAINTAINER_pn-xfd = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xfontsel = "red"
RECIPE_LATEST_VERSION_pn-xfontsel = "1.0.2"
RECIPE_MAINTAINER_pn-xfontsel = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xgamma = "red"
RECIPE_LATEST_VERSION_pn-xgamma = "1.0.3"
RECIPE_MAINTAINER_pn-xgamma = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xkbevd = "red"
RECIPE_LATEST_VERSION_pn-xkbevd = "1.1.0"
RECIPE_MAINTAINER_pn-xkbevd = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xkbprint = "red"
RECIPE_LATEST_VERSION_pn-xkbprint = "1.0.2"
RECIPE_MAINTAINER_pn-xkbprint = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xkbutils = "red"
RECIPE_LATEST_VERSION_pn-xkbutils = "1.0.2"
RECIPE_MAINTAINER_pn-xkbutils = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xkill = "red"
RECIPE_LATEST_VERSION_pn-xkill = "1.0.2"
RECIPE_MAINTAINER_pn-xkill = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xload = "red"
RECIPE_LATEST_VERSION_pn-xload = "1.0.2"
RECIPE_MAINTAINER_pn-xload = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xlsatoms = "red"
RECIPE_LATEST_VERSION_pn-xlsatoms = "1.1.0"
RECIPE_MAINTAINER_pn-xlsatoms = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xlsclients = "red"
RECIPE_LATEST_VERSION_pn-xlsclients = "1.1.0"
RECIPE_MAINTAINER_pn-xlsclients = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xlsfonts = "red"
RECIPE_LATEST_VERSION_pn-xlsfonts = "1.0.2"
RECIPE_MAINTAINER_pn-xlsfonts = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xmag = "red"
RECIPE_LATEST_VERSION_pn-xmag = "1.0.3"
RECIPE_MAINTAINER_pn-xmag = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xmessage = "red"
RECIPE_LATEST_VERSION_pn-xmessage = "1.0.3"
RECIPE_MAINTAINER_pn-xmessage = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xrdb = "red"
RECIPE_LATEST_VERSION_pn-xrdb = "1.0.6"
RECIPE_MAINTAINER_pn-xrdb = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xrefresh = "red"
RECIPE_LATEST_VERSION_pn-xrefresh = "1.0.3"
RECIPE_MAINTAINER_pn-xrefresh = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xsetroot = "red"
RECIPE_LATEST_VERSION_pn-xsetroot = "1.0.3"
RECIPE_MAINTAINER_pn-xsetroot = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xstdcmap = "red"
RECIPE_LATEST_VERSION_pn-xstdcmap = "1.0.1"
RECIPE_MAINTAINER_pn-xstdcmap = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xtrap = "red"
RECIPE_LATEST_VERSION_pn-xtrap = "1.0.2"
RECIPE_MAINTAINER_pn-xtrap = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xvidtune = "red"
RECIPE_LATEST_VERSION_pn-xvidtune = "1.0.2"
RECIPE_MAINTAINER_pn-xvidtune = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xvinfo = "red"
RECIPE_LATEST_VERSION_pn-xvinfo = "1.1.0"
RECIPE_MAINTAINER_pn-xvinfo = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xwd = "red"
RECIPE_LATEST_VERSION_pn-xwd = "1.0.3"
RECIPE_MAINTAINER_pn-xwd = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-xwud = "red"
RECIPE_LATEST_VERSION_pn-xwud = "1.0.2"
RECIPE_MAINTAINER_pn-xwud = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-claws-plugin-gtkhtml2-viewer = "red"
RECIPE_LATEST_VERSION_pn-claws-plugin-gtkhtml2-viewer = "0.27"
RECIPE_MAINTAINER_pn-claws-plugin-gtkhtml2-viewer = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-claws-plugin-maildir = "red"
RECIPE_LATEST_VERSION_pn-claws-plugin-maildir = "0.24.4"
RECIPE_MAINTAINER_pn-claws-plugin-maildir = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-claws-plugin-mailmbox = "red"
RECIPE_LATEST_VERSION_pn-claws-plugin-mailmbox = "1.14.4"
RECIPE_MAINTAINER_pn-claws-plugin-mailmbox = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-claws-plugin-rssyl = "red"
RECIPE_LATEST_VERSION_pn-claws-plugin-rssyl = "0.27"
RECIPE_MAINTAINER_pn-claws-plugin-rssyl = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-lndir = "red"
RECIPE_LATEST_VERSION_pn-lndir = "n/a"
RECIPE_MAINTAINER_pn-lndir = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-mozilla-headless = "red"
RECIPE_LATEST_VERSION_pn-mozilla-headless = "tip_hg_555cbc23"
RECIPE_MAINTAINER_pn-mozilla-headless = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-kf = "red"
RECIPE_LATEST_VERSION_pn-kf = "n/a"
RECIPE_MAINTAINER_pn-kf = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-claws-mail = "red"
RECIPE_LATEST_VERSION_pn-claws-mail = "3.7.6"
RECIPE_MAINTAINER_pn-claws-mail = "Edwin Zhai <edwin.zhai@intel.com>"

RECIPE_STATUS_pn-x11vnc = "red"
RECIPE_LATEST_VERSION_pn-x11vnc = "0.9.11_dev"
RECIPE_MAINTAINER_pn-x11vnc = "Edwin Zhai <edwin.zhai@intel.com>"
