#
# distro tracking fields for X11 UX
#

RECIPE_STATUS_pn-gnome-mime-data = "green" # no update needed
DEPENDENCY_CHECK_pn-gnome-mime-data = "not done"
RECIPE_LATEST_VERSION_pn-gnome-mime-data = "2.18.0"
RECIPE_NO_OF_PATCHES_pn-gnome-mime-data = "1"
RECIPE_INTEL_SECTION_pn-gnome-mime-data = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-gnome-mime-data = "5 months"
RECIPE_LATEST_RELEASE_DATE_pn-gnome-mime-data = "04/2007"
RECIPE_COMMENTS_pn-gnome-mime-data = ""

RECIPE_STATUS_pn-libmatchbox = "green" # no update needed
DEPENDENCY_CHECK_pn-libmatchbox = "not done"
RECIPE_LATEST_VERSION_pn-libmatchbox = "1.9"
RECIPE_NO_OF_PATCHES_pn-libmatchbox = "2"
RECIPE_INTEL_SECTION_pn-libmatchbox = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libmatchbox = "5 months"
RECIPE_LATEST_RELEASE_DATE_pn-libmatchbox = "08/2006"
RECIPE_COMMENTS_pn-libmatchbox = ""

RECIPE_STATUS_pn-libowl = "green" # no update needed
DEPENDENCY_CHECK_pn-libowl = "not done"
RECIPE_LATEST_VERSION_pn-libowl = "408"
RECIPE_NO_OF_PATCHES_pn-libowl = "0"
RECIPE_INTEL_SECTION_pn-libowl = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libowl = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-libowl = "09/2008"
RECIPE_COMMENTS_pn-libowl = ""

RECIPE_STATUS_pn-libowl-av = "green" # no update needed
DEPENDENCY_CHECK_pn-libowl-av = "not done"
RECIPE_LATEST_VERSION_pn-libowl-av = "398"
RECIPE_NO_OF_PATCHES_pn-libowl-av = "0"
RECIPE_INTEL_SECTION_pn-libowl-av = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libowl-av = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-libowl-av = "12/2008"
RECIPE_COMMENTS_pn-libowl-av = ""

RECIPE_STATUS_pn-matchbox-desktop = "green" # no update needed
DEPENDENCY_CHECK_pn-matchbox-desktop = "not done"
RECIPE_LATEST_VERSION_pn-matchbox-desktop = "2096"
RECIPE_NO_OF_PATCHES_pn-matchbox-desktop = "0"
RECIPE_INTEL_SECTION_pn-matchbox-desktop = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-matchbox-desktop = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-matchbox-desktop = "12/2008"
RECIPE_COMMENTS_pn-matchbox-desktop = ""

RECIPE_STATUS_pn-matchbox-desktop-sato = "green" # no update needed
DEPENDENCY_CHECK_pn-matchbox-desktop-sato = "not done"
RECIPE_LATEST_VERSION_pn-matchbox-desktop-sato = "76"
RECIPE_NO_OF_PATCHES_pn-matchbox-desktop-sato = "0"
RECIPE_INTEL_SECTION_pn-matchbox-desktop-sato = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-matchbox-desktop-sato = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-matchbox-desktop-sato = "07/2007"
RECIPE_COMMENTS_pn-matchbox-desktop-sato = ""

RECIPE_STATUS_pn-matchbox-session = "green" # no update needed
DEPENDENCY_CHECK_pn-matchbox-session = "not done"
RECIPE_LATEST_VERSION_pn-matchbox-session = "0.1"
RECIPE_NO_OF_PATCHES_pn-matchbox-session = "0"
RECIPE_INTEL_SECTION_pn-matchbox-session = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-matchbox-session = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-matchbox-session = "02/2004"
RECIPE_COMMENTS_pn-matchbox-session = ""

RECIPE_STATUS_pn-matchbox-session-sato = "green" # no update needed
DEPENDENCY_CHECK_pn-matchbox-session-sato = "not done"
RECIPE_LATEST_VERSION_pn-matchbox-session-sato = "0.1"
RECIPE_NO_OF_PATCHES_pn-matchbox-session-sato = "0"
RECIPE_INTEL_SECTION_pn-matchbox-session-sato = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-matchbox-session-sato = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-matchbox-session-sato = "06/2007"
RECIPE_COMMENTS_pn-matchbox-session-sato = ""

RECIPE_STATUS_pn-matchbox-terminal = "green" # no update needed
DEPENDENCY_CHECK_pn-matchbox-terminal = "not done"
RECIPE_LATEST_VERSION_pn-matchbox-terminal = "1816"
RECIPE_NO_OF_PATCHES_pn-matchbox-terminal = "0"
RECIPE_INTEL_SECTION_pn-matchbox-terminal = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-matchbox-terminal = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-matchbox-terminal = "11/2007"
RECIPE_COMMENTS_pn-matchbox-terminal = ""

RECIPE_STATUS_pn-matchbox-theme-sato = "green" # no update needed
DEPENDENCY_CHECK_pn-matchbox-theme-sato = "not done"
RECIPE_LATEST_VERSION_pn-matchbox-theme-sato = "0.1"
RECIPE_NO_OF_PATCHES_pn-matchbox-theme-sato = "0"
RECIPE_INTEL_SECTION_pn-matchbox-theme-sato = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-matchbox-theme-sato = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-matchbox-theme-sato = "07/2007"
RECIPE_COMMENTS_pn-matchbox-theme-sato = ""

RECIPE_STATUS_pn-sato-icon-theme = "green" # no update needed
DEPENDENCY_CHECK_pn-sato-icon-theme = "not done"
RECIPE_LATEST_VERSION_pn-sato-icon-theme = "0.4.1"
RECIPE_NO_OF_PATCHES_pn-sato-icon-theme = "0"
RECIPE_INTEL_SECTION_pn-sato-icon-theme = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-sato-icon-theme = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-sato-icon-theme = "02/2008"
RECIPE_COMMENTS_pn-sato-icon-theme = ""

RECIPE_STATUS_pn-tslib = "green" # no update needed
DEPENDENCY_CHECK_pn-tslib = "not done"
RECIPE_LATEST_VERSION_pn-tslib = "1.0"
RECIPE_NO_OF_PATCHES_pn-tslib = "3"
RECIPE_INTEL_SECTION_pn-tslib = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-tslib = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-tslib = "08/2006"
RECIPE_COMMENTS_pn-tslib = ""

RECIPE_STATUS_pn-xcursor-transparent-theme = "green" # no update needed
DEPENDENCY_CHECK_pn-xcursor-transparent-theme = "not done"
RECIPE_LATEST_VERSION_pn-xcursor-transparent-theme = "0.1.1"
RECIPE_NO_OF_PATCHES_pn-xcursor-transparent-theme = "2"
RECIPE_INTEL_SECTION_pn-xcursor-transparent-theme = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xcursor-transparent-theme = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-xcursor-transparent-theme = "12/2004"
RECIPE_COMMENTS_pn-xcursor-transparent-theme = ""

RECIPE_STATUS_pn-screenshot = "green"
DEPENDENCY_CHECK_pn-screenshot = "not done"
RECIPE_LATEST_VERSION_pn-screenshot = "292"
RECIPE_NO_OF_PATCHES_pn-screenshot = "0"
RECIPE_INTEL_SECTION_pn-screenshot = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-screenshot = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-screenshot = "09/2007"
RECIPE_COMMENTS_pn-screenshot = ""

RECIPE_STATUS_pn-tasks = "green"
DEPENDENCY_CHECK_pn-tasks = "not done"
RECIPE_LATEST_VERSION_pn-tasks = "0.16"
RECIPE_NO_OF_PATCHES_pn-tasks = "1"
RECIPE_INTEL_SECTION_pn-tasks = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-tasks = "4 months"
RECIPE_LATEST_RELEASE_DATE_pn-tasks = "07/2009"
RECIPE_COMMENTS_pn-tasks = ""

RECIPE_STATUS_pn-contacts = "green"
DEPENDENCY_CHECK_pn-contacts = "not done"
RECIPE_LATEST_VERSION_pn-contacts = "0.12+19853893f"
RECIPE_NO_OF_PATCHES_pn-contacts = "1"
RECIPE_INTEL_SECTION_pn-contacts = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-contacts = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-contacts = "11/2009"
RECIPE_COMMENTS_pn-contacts = ""

RECIPE_STATUS_pn-dates = "green"
DEPENDENCY_CHECK_pn-dates = "not done"
RECIPE_LATEST_VERSION_pn-dates = "0.4.11+514185dc"
RECIPE_NO_OF_PATCHES_pn-dates = "1"
RECIPE_INTEL_SECTION_pn-dates = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-dates = "1 month"
RECIPE_LATEST_RELEASE_DATE_pn-dates = "10/2009"
RECIPE_COMMENTS_pn-dates = ""

RECIPE_STATUS_pn-libcroco = "green"
DEPENDENCY_CHECK_pn-libcroco = "not done"
RECIPE_LATEST_VERSION_pn-libcroco = "0.6.2"
RECIPE_NO_OF_PATCHES_pn-libcroco = "1"
RECIPE_INTEL_SECTION_pn-libcroco = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libcroco = "35 months"
RECIPE_LATEST_RELEASE_DATE_pn-libcroco = "02/2009"
RECIPE_COMMENTS_pn-libcroco = ""

RECIPE_STATUS_pn-leafpad = "green"
DEPENDENCY_CHECK_pn-leafpad = "not done"
RECIPE_LATEST_VERSION_pn-leafpad = "0.8.17"
RECIPE_NO_OF_PATCHES_pn-leafpad = "1"
RECIPE_INTEL_SECTION_pn-leafpad = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-leafpad = "10 months"
RECIPE_LATEST_RELEASE_DATE_pn-leafpad = "10/2009"
RECIPE_COMMENTS_pn-leafpad = ""

RECIPE_STATUS_pn-atk = "green"
DEPENDENCY_CHECK_pn-atk = "not done"
RECIPE_LATEST_VERSION_pn-atk = "1.30.0"
RECIPE_NO_OF_PATCHES_pn-atk = "0"
RECIPE_INTEL_SECTION_pn-atk = "graphic UX"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-atk = "1 month"
RECIPE_LATEST_RELEASE_DATE_pn-atk = "03/2010"
RECIPE_COMMENTS_pn-atk = ""

