RECIPE_STATUS_pn-lrzsz="yellow" # patch investigation needed.
RECIPE_LATEST_VERSION_pn-lrzsz="0.12.20"
RECIPE_NO_OF_PATCHES_pn-lrzsz="3"
RECIPE_LATEST_RELEASE_DATE_pn-lrzsz="1998/12/31"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-lrzsz="12 months"

RECIPE_STATUS_pn-wireless-tools="yellow" # patch investigation needed
RECIPE_LATEST_VERSION_pn-wireless-tools="29"
RECIPE_NO_OF_PATCHES_pn-wireless-tools="3"
RECIPE_LATEST_RELEASE_DATE_pn-wireless-tools="2007/09/18"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-wireless-tools="18 months"

RECIPE_STATUS_pn-bluez-dtl1-workaround="yellow" # LICENSE double check
RECIPE_LATEST_VERSION_pn-bluez-dtl1-workaround="1.0"
RECIPE_NO_OF_PATCHES_pn-bluez-dtl1-workaround="0"
RECIPE_LATEST_RELEASE_DATE_pn-bluez-dtl1-workaround="n/a"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-bluez-dtl1-workaround="n/a"

RECIPE_STATUS_pn-irda-utils="green"
RECIPE_LATEST_VERSION_pn-irda-utils="0.9.18"
RECIPE_NO_OF_PATCHES_pn-irda-utils="0"
RECIPE_LATEST_RELEASE_DATE_pn-irda-utils="2006/07/10"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-irda-utils="4 months"

RECIPE_STATUS_pn-bluez4="green"
RECIPE_LATEST_VERSION_pn-bluez4="4.66"
RECIPE_NO_OF_PATCHES_pn-bluez4="2"
RECIPE_LATEST_RELEASE_DATE_pn-bluez4="2010/05/24"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-bluez4="1 month"

RECIPE_STATUS_pn-libpcap="green"
RECIPE_LATEST_VERSION_pn-libpcap="1.1.1"
RECIPE_NO_OF_PATCHES_pn-libpcap="2"
RECIPE_LATEST_RELEASE_DATE_pn-libpcap="2010/04/05"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libpcap="2 months"

RECIPE_STATUS_pn-wpa-supplicant="green"
RECIPE_LATEST_VERSION_pn-wpa-supplicant="0.7.2"
RECIPE_NO_OF_PATCHES_pn-wpa-supplicant="0"
RECIPE_LATEST_RELEASE_DATE_pn-wpa-supplicant="2010/04/18"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-wpa-supplicant="3 months"

RECIPE_STATUS_pn-ppp="green"
RECIPE_LATEST_VERSION_pn-ppp="2.4.5"
RECIPE_NO_OF_PATCHES_pn-ppp="5"
RECIPE_LATEST_RELEASE_DATE_pn-ppp="2009/11/17"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-ppp="4 years"

RECIPE_STATUS_pn-libproxy="red" # Need upgrade
RECIPE_LATEST_VERSION_pn-libproxy="0.4.4" # OK
RECIPE_NO_OF_PATCHES_pn-libproxy="1"
RECIPE_LATEST_RELEASE_DATE_pn-libproxy="2010/05/19"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libproxy="3 months"

RECIPE_STATUS_pn-networkmanager="red" # Need upgrade
RECIPE_LATEST_VERSION_pn-networkmanager="0.8" # OK
RECIPE_NO_OF_PATCHES_pn-networkmanager="4"
RECIPE_LATEST_RELEASE_DATE_pn-networkmanager="2010/04/18"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-networkmanager="3 months"

RECIPE_STATUS_pn-networkmanager-applet="red" # Need upgrade
RECIPE_LATEST_VERSION_pn-networkmanager-applet="n/a" # OK
RECIPE_NO_OF_PATCHES_pn-networkmanager-applet="4"
RECIPE_LATEST_RELEASE_DATE_pn-networkmanager-applet="n/a"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-networkmanager-applet="n/a"
