RECIPE_STATUS_pn-liba52="yellow" # patch investigation needed
RECIPE_LATEST_VERSION_pn-liba52="0.7.4"
RECIPE_NO_OF_PATCHES_pn-liba52="1"
RECIPE_LATEST_RELEASE_DATE_pn-liba52="2002/07/27"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-liba52="5 months"

RECIPE_STATUS_pn-libid3tag="yellow" # patch investigation needed
RECIPE_LATEST_VERSION_pn-libid3tag="0.15.1b"
RECIPE_NO_OF_PATCHES_pn-libid3tag="1"
RECIPE_LATEST_RELEASE_DATE_pn-libid3tag="2004/02/18"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libid3tag="8 months"

RECIPE_STATUS_pn-libmad="yellow" # patch investigation needed
RECIPE_LATEST_VERSION_pn-libmad="0.15.1b"
RECIPE_NO_OF_PATCHES_pn-libmad="2"
RECIPE_LATEST_RELEASE_DATE_pn-libmad="2004/02/18"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libmad="8 months"


