#
# distro tracking fields for X11 apps packages
#

RECIPE_STATUS_pn-mkfontdir="green" # no update needed
RECIPE_LATEST_VERSION_pn-mkfontdir="1.0.5"
RECIPE_NO_OF_PATCHES_pn-mkfontdir="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-mkfontdir="2009/10/11"
RECIPE_LATEST_RELEASE_DATE_pn-mkfontdir="16 monthes"
RECIPE_INTEL_SECTION_pn-mkfontdir="graphic apps"
RECIPE_MAINTAINER_pn-mkfontdir="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-mkfontscale="green" # no update needed
RECIPE_LATEST_VERSION_pn-mkfontscale="1.0.7"
RECIPE_NO_OF_PATCHES_pn-mkfontscale="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-mkfontscale="10 monthes"
RECIPE_LATEST_RELEASE_DATE_pn-mkfontscale="2009/10/11"
RECIPE_INTEL_SECTION_pn-mkfontscale="graphic apps"
RECIPE_MAINTAINER_pn-mkfontscale="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-xauth="green" # no update needed
RECIPE_LATEST_VERSION_pn-xauth="1.0.4"
RECIPE_NO_OF_PATCHES_pn-xauth="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xauth="1 year"
RECIPE_LATEST_RELEASE_DATE_pn-xauth="2009/09/21"
RECIPE_INTEL_SECTION_pn-xauth="graphic app"
RECIPE_MAINTAINER_pn-xauth="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-xdpyinfo="green" # no update needed
RECIPE_LATEST_VERSION_pn-xdpyinfo="1.1.0"
RECIPE_NO_OF_PATCHES_pn-xdpyinfo="1"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xdpyinfo="1 year"
RECIPE_LATEST_RELEASE_DATE_pn-xdpyinfo="2009/10/16"
RECIPE_INTEL_SECTION_pn-xdpyinfo="graphic app"
RECIPE_MAINTAINER_pn-xdpyinfo="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-xhost="green" # no update needed
RECIPE_LATEST_VERSION_pn-xhost="1.0.3"
RECIPE_NO_OF_PATCHES_pn-xhost="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xhost="2 years"
RECIPE_LATEST_RELEASE_DATE_pn-xhost="2009/10/14"
RECIPE_INTEL_SECTION_pn-xhost="graphic app"
RECIPE_MAINTAINER_pn-xhost="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-xinit="green" # no update needed
RECIPE_LATEST_VERSION_pn-xinit="1.2.1"
RECIPE_NO_OF_PATCHES_pn-xinit="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xinit="4 monthes"
RECIPE_LATEST_RELEASE_DATE_pn-xinit="2010/03/16"
RECIPE_INTEL_SECTION_pn-xinit="graphic app"
RECIPE_MAINTAINER_pn-xinit="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-xkbcomp="green" # no update needed
RECIPE_LATEST_VERSION_pn-xkbcomp="1.1.1"
RECIPE_NO_OF_PATCHES_pn-xkbcomp="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xkbcomp="2 monthes"
RECIPE_LATEST_RELEASE_DATE_pn-xkbcomp="2009/10/03"
RECIPE_INTEL_SECTION_pn-xkbcomp="graphic app"
RECIPE_MAINTAINER_pn-xkbcomp="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-xmodmap="green" # no update needed
RECIPE_LATEST_VERSION_pn-xmodmap="1.0.4"
RECIPE_NO_OF_PATCHES_pn-xmodmap="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xmodmap="2 years"
RECIPE_LATEST_RELEASE_DATE_pn-xmodmap="2009/10/06"
RECIPE_INTEL_SECTION_pn-xmodmap="graphic app"
RECIPE_MAINTAINER_pn-xmodmap="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-xprop="green" # no update needed
RECIPE_LATEST_VERSION_pn-xprop="1.1.0"
RECIPE_NO_OF_PATCHES_pn-xprop="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xprop="1 year"
RECIPE_LATEST_RELEASE_DATE_pn-xprop="2009/10/12"
RECIPE_INTEL_SECTION_pn-xprop="graphic app"
RECIPE_MAINTAINER_pn-xprop="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-xset="green" # no update needed
DISTRO_PN_ALIAS_pn-xset = "Fedora=xorg-x11-server-utils Ubuntu=x11-xserver-utils Debian=x11-xserver-utils Opensuse=xorg-x11"
RECIPE_LATEST_VERSION_pn-xset="1.1.0"
RECIPE_NO_OF_PATCHES_pn-xset="1"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xset="1 year"
RECIPE_LATEST_RELEASE_DATE_pn-xset="2009/09/21"
RECIPE_INTEL_SECTION_pn-xset="graphic app"
RECIPE_MAINTAINER_pn-xset="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-xwininfo="green" # no update needed
RECIPE_LATEST_VERSION_pn-xwininfo="1.0.5"
RECIPE_NO_OF_PATCHES_pn-xwininfo="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xwininfo="1 year"
RECIPE_LATEST_RELEASE_DATE_pn-xwininfo="2009/10/12"
RECIPE_INTEL_SECTION_pn-xwininfo="graphic app"
RECIPE_MAINTAINER_pn-xwininfo="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-xrandr="green" # no update needed
RECIPE_LATEST_VERSION_pn-xrandr="1.3.2"
RECIPE_NO_OF_PATCHES_pn-xrandr="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xrandr="1 month"
RECIPE_LATEST_RELEASE_DATE_pn-xrandr="2009/09/10"
RECIPE_INTEL_SECTION_pn-xrandr="graphic app"
RECIPE_MAINTAINER_pn-xrandr="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-vte="green" # no update needed
RECIPE_LATEST_VERSION_pn-vte="0.24.3"
RECIPE_NO_OF_PATCHES_pn-vte="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-vte="3 monthes"
RECIPE_LATEST_RELEASE_DATE_pn-vte="2010/07/12"
RECIPE_INTEL_SECTION_pn-vte="graphic app"
RECIPE_MAINTAINER_pn-vte="Yu Ke <ke.yu@intel.com>"

RECIPE_STATUS_pn-qemugl="green" # no update needed
RECIPE_LATEST_VERSION_pn-qemugl="0.0+git0+d888bbc723c00d197d34a39b5b7448660ec1b1c0"
RECIPE_NO_OF_PATCHES_pn-qemugl="1"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-qemugl="n/a"
RECIPE_LATEST_RELEASE_DATE_pn-qemugl="2009/05/30"
RECIPE_INTEL_SECTION_pn-qemugl="graphic app"
RECIPE_MAINTAINER_pn-qemugl="Yu Ke <ke.yu@intel.com>"
