RECIPE_STATUS_pn-hostap-utils="yellow" # patch investigation needed; hostap-utils.inc is only included by one bb file.
RECIPE_LATEST_VERSION_pn-hostap-utils="0.4.7"
RECIPE_NO_OF_PATCHES_pn-hostap-utils="1"
RECIPE_LATEST_RELEASE_DATE_pn-hostap-utils="2008/12/03"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-hostap-utils="7 months"

RECIPE_STATUS_pn-kexec-tools="green"
RECIPE_LATEST_VERSION_pn-kexec-tools="2.0.1"
RECIPE_NO_OF_PATCHES_pn-kexec-tools="1"
RECIPE_LATEST_RELEASE_DATE_pn-kexec-tools="2009/08/12"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-kexec-tools="1 year"
