#
# distro tracking filed for X core packages
#

RECIPE_STATUS_pn-bigreqsproto="green" # no update needed
RECIPE_LATEST_VERSION_pn-bigreqsproto="1.1.0"
RECIPE_NO_OF_PATCHES_pn-bigreqsproto="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-bigreqsproto="3 years"
RECIPE_LATEST_RELEASE_DATE_pn-bigreqsproto="2009/08/26"
RECIPE_INTEL_SECTION_pn-bigreqsproto="graphic core"

RECIPE_STATUS_pn-evieext="green" # no update needed
RECIPE_LATEST_VERSION_pn-evieext="1.1.0"
RECIPE_NO_OF_PATCHES_pn-evieext="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-evieext="3 years"
RECIPE_LATEST_RELEASE_DATE_pn-evieext="2009/08/26"
RECIPE_INTEL_SECTION_pn-evieext="graphic core"

RECIPE_STATUS_pn-libxxf86dga="green" # no update needed
RECIPE_LATEST_VERSION_pn-libxxf86dga="1.1.1"
RECIPE_NO_OF_PATCHES_pn-libxxf86dga="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libxxf86dga="1 month"
RECIPE_LATEST_RELEASE_DATE_pn-libxxf86dga="2009/10/06"
RECIPE_INTEL_SECTION_pn-libxxf86dga="graphic core"

RECIPE_STATUS_pn-x11-common="green" # no update needed
RECIPE_LATEST_VERSION_pn-x11-common="0.1"
RECIPE_NO_OF_PATCHES_pn-x11-common="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-x11-common="n/a" # local file without release
RECIPE_LATEST_RELEASE_DATE_pn-x11-common="2008/09/22" # per poky git log
RECIPE_INTEL_SECTION_pn-x11-common="graphic core"

RECIPE_STATUS_pn-xf86-input-keyboard="green" # no update needed
RECIPE_LATEST_VERSION_pn-xf86-input-keyboard="1.4.0"
RECIPE_NO_OF_PATCHES_pn-xf86-input-keyboard="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xf86-input-keyboard="9 monthes"
RECIPE_LATEST_RELEASE_DATE_pn-xf86-input-keyboard="2009/10/07"
RECIPE_INTEL_SECTION_pn-xf86-input-keyboard="graphic core"

RECIPE_STATUS_pn-xf86-input-mouse="green" # no update needed
RECIPE_LATEST_VERSION_pn-xf86-input-mouse="1.5.0"
RECIPE_NO_OF_PATCHES_pn-xf86-input-mouse="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xf86-input-mouse="9 monthes"
RECIPE_LATEST_RELEASE_DATE_pn-xf86-input-mouse="2009/10/06"
RECIPE_INTEL_SECTION_pn-xf86-input-mouse="graphic core"

RECIPE_STATUS_pn-xf86-input-vmmouse="red" # update needed
RECIPE_LATEST_VERSION_pn-xf86-input-vmmouse="12.6.9"
RECIPE_NO_OF_PATCHES_pn-xf86-input-vmmouse="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xf86-input-vmmouse="1 month"
RECIPE_LATEST_RELEASE_DATE_pn-xf86-input-vmmouse="2010/04/08"
RECIPE_INTEL_SECTION_pn-xf86-input-vmmouse="graphic core"

RECIPE_STATUS_pn-libdrm="green" # no update needed
RECIPE_LATEST_VERSION_pn-libdrm="2.4.21"
RECIPE_NO_OF_PATCHES_pn-libdrm="1"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libdrm="1 month"
RECIPE_LATEST_RELEASE_DATE_pn-libdrm="2010/06/10"
RECIPE_INTEL_SECTION_pn-libdrm="graphic core"

RECIPE_STATUS_pn-python-pycairo="red" # upgrade needed. src file name changed to py2cairo
RECIPE_LATEST_VERSION_pn-python-pycairo="1.8.10"
RECIPE_NO_OF_PATCHES_pn-python-pycairo="0"
RECIPE_LATEST_RELEASE_DATE_pn-python-pycairo="2010/05/20"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-python-pycairo="9 months"

RECIPE_STATUS_pn-libxfontcache="green" # no update neededd
RECIPE_LATEST_VERSION_pn-libxfontcache="1.0.5"
RECIPE_NO_OF_PATCHES_pn-libxfontcache="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-libxfontcache="3 years"
RECIPE_LATEST_RELEASE_DATE_pn-libxfontcache="2009/10/08"
RECIPE_INTEL_SECTION_pn-libxfontcache="graphic core"
