#
# distro tracking fields for X11 apps packages
#

RECIPE_STATUS_pn-mkfontdir="green" # no update needed
RECIPE_LATEST_VERSION_pn-mkfontdir="1.0.5"
RECIPE_NO_OF_PATCHES_pn-mkfontdir="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-mkfontdir="2009/10/11"
RECIPE_LATEST_RELEASE_DATE_pn-mkfontdir="16 monthes"
RECIPE_INTEL_SECTION_pn-mkfontdir="graphic apps"

RECIPE_STATUS_pn-mkfontscale="green" # no update needed
RECIPE_LATEST_VERSION_pn-mkfontscale="1.0.7"
RECIPE_NO_OF_PATCHES_pn-mkfontscale="0"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-mkfontscale="10 monthes"
RECIPE_LATEST_RELEASE_DATE_pn-mkfontscale="2009/10/11"
RECIPE_INTEL_SECTION_pn-mkfontscale="graphic apps"
