#
# distro tracking fields for X11 apps(high level)
#

RECIPE_STATUS_pn-owl-video = "green" # no update needed
DEPENDENCY_CHECK_pn-owl-video = "not done"
RECIPE_LATEST_VERSION_pn-owl-video = "394"
RECIPE_NO_OF_PATCHES_pn-owl-video = "0"
RECIPE_INTEL_SECTION_pn-owl-video = "graphic apps"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-owl-video = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-owl-video = "06/2008"
RECIPE_COMMENTS_pn-owl-video = ""

RECIPE_STATUS_pn-xtscal = "green" # no update needed
DEPENDENCY_CHECK_pn-xtscal = "not done"
RECIPE_LATEST_VERSION_pn-xtscal = "0.6.3"
RECIPE_NO_OF_PATCHES_pn-xtscal = "2"
RECIPE_INTEL_SECTION_pn-xtscal = "graphic apps"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xtscal = "n/a"
RECIPE_LATEST_RELEASE_DATE_pn-xtscal = "06/2006"
RECIPE_COMMENTS_pn-xtscal = ""

RECIPE_STATUS_pn-xrestop = "green" # no update needed
DEPENDENCY_CHECK_pn-xrestop = "not done"
RECIPE_LATEST_VERSION_pn-xrestop = "0.4"
RECIPE_NO_OF_PATCHES_pn-xrestop = "0"
RECIPE_INTEL_SECTION_pn-xrestop = "graphic apps"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-xrestop = "18 months"
RECIPE_LATEST_RELEASE_DATE_pn-xrestop = "03/2006"
RECIPE_COMMENTS_pn-xrestop = ""

RECIPE_STATUS_pn-pcmanfm = "yellow" # update needed
DEPENDENCY_CHECK_pn-pcmanfm = "not done"
RECIPE_LATEST_VERSION_pn-pcmanfm = "0.9.7"
RECIPE_NO_OF_PATCHES_pn-pcmanfm = "4"
RECIPE_INTEL_SECTION_pn-pcmanfm = "graphic apps"
RECIPE_TIME_BETWEEN_LAST_TWO_RELEASES_pn-pcmanfm = "4 months"
RECIPE_LATEST_RELEASE_DATE_pn-pcmanfm = "05/2010"
RECIPE_COMMENTS_pn-pcmanfm = ""

