#! /bin/sh
#
# Copyright Matthias Hentges <devel@hentges.net> (c) 2007
# License: GPL (see http://www.gnu.org/licenses/gpl.txt for a copy of the license)
#
# Filename: alsa-state
# Date: 20070308 (YMD)


asound_restore(){
	echo "ALSA: Restoring mixer settings..."
	if test -x /usr/sbin/alsactl -a -e /etc/asound.state
	then
		/usr/sbin/alsactl -f /etc/asound.state restore &
	fi
}

asound_store(){
	echo "ALSA: Storing mixer settings..."
	if test -x /usr/sbin/alsactl
	then
		/usr/sbin/alsactl -f /etc/asound.state store
	fi
}

case "$1" in
start)		asound_restore ;;
stop)		asound_store ;;
esac
