Index: perl-5.8.8/Cross/Makefile
===================================================================
--- perl-5.8.8.orig/Cross/Makefile	2004-01-12 21:44:01.000000000 +0100
+++ perl-5.8.8/Cross/Makefile	2007-08-15 00:15:18.000000000 +0200
@@ -2,7 +2,8 @@
 #
 ## $Id: Makefile,v 1.7 2004/01/12 15:41:02 red Exp red $
 
-export TOPDIR=${shell pwd}
+override TOPDIR=${shell pwd}
+export TOPDIR
 include $(TOPDIR)/config
 export CFLAGS
 export SYS=$(ARCH)-$(OS)
@@ -12,7 +13,7 @@
 
 export CC = $(CROSS)gcc
 export CXX = $(CROSS)g++
-export LD = $(CROSS)ld
+export LD = $(CC)
 export STRIP = $(CROSS)strip
 export AR = $(CROSS)ar
 export RANLIB = $(CROSS)ranlib
@@ -34,21 +35,6 @@
 all:
 	@echo Please read the README file before doing anything else.
 
-gen_patch:
-	diff -Bbur ../Makefile.SH Makefile.SH > Makefile.SH.patch
-	diff -Bbur ../installperl installperl > installperl.patch
-
-patch:
-	cd .. ; if [ ! -e ./CROSS_PATCHED ] ; then \
-		patch -p1 < Cross/Makefile.SH.patch; \
-		patch -p1 < Cross/installperl.patch ; mv installperl installperl-patched; \
-		sed -e 's/XXSTRIPXX/$(SYS)/' installperl-patched > installperl; \
-		touch CROSS_PATCHED ; fi
-
-dry_patch:
-	cd .. ;	patch --dry-run -p1 < Cross/Makefile.SH.patch; \
-		patch --dry-run -p1 < Cross/installperl.patch; \
-
 perl:
 	@echo Perl cross-build directory is $(TOPDIR)
 	@echo Target arch is $(SYS)
@@ -58,11 +44,11 @@
 	$(TOPDIR)/generate_config_sh config.sh-$(SYS) > $(TOPDIR)/../config.sh
 	cd $(TOPDIR)/.. ; ./Configure -S ; make depend ; make ; make more
 	cd $(TOPDIR)/.. ; mkdir -p fake_config_library ; cp lib/Config.pm fake_config_library
-	cd $(TOPDIR)/.. ; $(MAKE) more2 "PERLRUN=/usr/bin/perl -I$(TOPDIR)/../fake_config_library -MConfig"
-	cd $(TOPDIR)/.. ; $(MAKE) more3 "PERLRUN=/usr/bin/perl -I$(TOPDIR)/../fake_config_library -MConfig"
-	cd $(TOPDIR)/.. ; $(MAKE) more4 "PERLRUN=/usr/bin/perl -I$(TOPDIR)/../fake_config_library -MConfig"
+	cd $(TOPDIR)/.. ; $(MAKE) more2 "PERLRUN=hostperl -I$(TOPDIR)/../fake_config_library -MConfig"
+	cd $(TOPDIR)/.. ; $(MAKE) more3 "PERLRUN=hostperl -I$(TOPDIR)/../fake_config_library -MConfig"
+	cd $(TOPDIR)/.. ; $(MAKE) more4 "PERLRUN=hostperl -I$(TOPDIR)/../fake_config_library -MConfig"
 	cd $(TOPDIR)/.. ; rm -rf install_me_here
-	cd $(TOPDIR)/.. ; make install-strip
+#	cd $(TOPDIR)/.. ; make install-strip
 	cd $(TOPDIR)/.. ; sh -x Cross/warp
 
 
