#
# Known good source dates/revisions/tags to use, for where Moblin deviates 
# from Poky:
#
PREFERRED_VERSION_dbus ?= "1.2.4"
PREFERRED_VERSION_dbus-native ?= "1.2.4"
PREFERRED_VERSION_eds-dbus ?= "2.20.0"
PREFERRED_VERSION_hal ?= "0.5.11"
PREFERRED_VERSION_hal-info ?= "20080508"

PREFERRED_VERSION_atk ?= "1.24.0"
PREFERRED_VERSION_pixman ?= "0.12.0"
PREFERRED_VERSION_cairo ?= "1.8.2"
PREFERRED_VERSION_pango ?= "1.22.2"
SRCREV_pn-xf86-video-psb ?= "b6b3bba06fe5a3fe0b1bd6e31a7369dd83812bab"
SRCREV_pn-libdrm-psb = "aa96c0bbbba11d5bab28bb421a67c2264fad953a"
SRCREV_pn-linux-mid ?= "cb29ee2997ba598028e1ad4bbdd073deac2d057d"