#
# Known good source dates/revisions/tags to use, for where Moblin deviates 
# from Poky:
#
PREFERRED_VERSION_eds-dbus ?= "2.20.0"
PREFERRED_VERSION_hal ?= "0.5.11"
PREFERRED_VERSION_hal-info ?= "20080508"

SRCREV_pn-xf86-video-psb ?= "b6b3bba06fe5a3fe0b1bd6e31a7369dd83812bab"
SRCREV_pn-libdrm-psb = "aa96c0bbbba11d5bab28bb421a67c2264fad953a"
SRCREV_pn-linux-mid ?= "cb29ee2997ba598028e1ad4bbdd073deac2d057d"
