#
# Known good source dates/revisions/tags to use, *only* for where Moblin deviates
# from Poky (or to lock down SCM based packages):
#
PREFERRED_VERSION_eds-dbus ?= "2.20.0"
PREFERRED_VERSION_dbus ?= "1.2.14"
PREFERRED_VERSION_dbus-native ?= "1.2.14"
PREFERRED_VERSION_gtk+ ?= "2.18.5"
PREFERRED_VERSION_pango = "1.26.0"
PREFERRED_VERSION_udev ?= "145"

PREFERRED_VERSION_mesa-dri ?= "7.8.2"
PREFERRED_VERSION_xf86-video-intel ?= "2.12.0"
PREFERRED_VERSION_xserver-xf86-dri-lite ?= "1.7.99.2"
PREFERRED_VERSION_libxcb ?= "1.3"
PREFERRED_VERSION_xcb-proto ?= "1.5"
PREFERRED_VERSION_libx11-trim ?= "1.3"

PREFERRED_VERSION_libdrm ?= "2.4.17"
PREFERRED_VERSION_xf86-input-keyboard ?= ""
PREFERRED_VERSION_dri2proto ?= ""


PREFERRED_VERSION_anerley ?= "0.1.7"
PREFERRED_VERSION_bickley ?= "0.4"
PREFERRED_VERSION_bisho ?= "0.17.1"
PREFERRED_VERSION_bognor-regis ?= "0.5.0"
PREFERRED_VERSION_carrick ?= "1.1.13"
PREFERRED_VERSION_dalston ?= "0.1.12"
PREFERRED_VERSION_gupnp-av ?= "0.4"
PREFERRED_VERSION_hornsey ?= "1.0"
PREFERRED_VERSION_mojito ?= "0.21.7"
PREFERRED_VERSION_nbtk ?= "1.2.3"
PREFERRED_VERSION_moblin-panel-applications ?= "0.1.2"
PREFERRED_VERSION_moblin-panel-media ?= "0.0.7"
PREFERRED_VERSION_moblin-panel-myzone ?= "0.0.12"
PREFERRED_VERSION_moblin-panel-pasteboard ?= "0.0.2"
PREFERRED_VERSION_moblin-panel-people ?= "0.0.9"
PREFERRED_VERSION_moblin-panel-status ?= "0.0.9"
PREFERRED_VERSION_mutter ?= "2.28.1"
PREFERRED_VERSION_mutter-moblin ?= "0.43.8"

