#!/bin/sh
# SPDX-License-Identifier: MIT

cd "$(dirname "$0")/tests" || exit 1

for t in *; do
    if ./"$t" >/dev/null 2>&1; then
        echo "PASS: $t"
    else
        echo "FAIL: $t"
    fi
done
