#!/bin/sh

if [ -z "$QEMU_MEMORY" ]
then
QEMU_MEMORY="64M"
fi

qemu-system-arm -kernel $1 -append "root=/dev/sda mem=$QEMU_MEMORY" -net nic,vlan=0 -net tap,vlan=0,ifname=tap0,script=./qemu-ifup -M versatilepb -hda $2