#!/bin/sh
qemu-system-arm -kernel $1 -append "root=/dev/nfs nfsroot=192.168.7.1:/srv/qemuarm rw ip=192.168.7.2::192.168.7.1:255.255.255.0 " -net nic,vlan=0 -net tap,vlan=0,ifname=tap0,script=./qemu-ifup
