#
# Copyright (C) 2023-2024 Siemens AG
#
# SPDX-License-Identifier: GPL-2.0-only
#
"""Devtool ide-sdk generic IDE plugin"""

import os
import logging
import stat
from bb.utils import mkdirhier
from devtool.ide_plugins import IdeBase, GdbCrossConfig, LldbServerConfig, DebuggerServerModes

logger = logging.getLogger('devtool')


class GdbCrossConfigNone(GdbCrossConfig):
    def __init__(self, image_recipe, modified_recipe, binary,
                 default_mode=DebuggerServerModes.MULTI):
        super().__init__(image_recipe, modified_recipe, binary,
                         default_mode)

    def _target_gdbserver_stop_cmd(self, server_mode):
        """Kill a gdbserver process

        Stopping is based on the PID file written by the start command. Other
        debug sessions run their own gdbserver on the target, so anything
        matching by process name would hit them as well.
        """
        pid_file = self._gdbserver_pid_file(server_mode)
        gdbserver_cmd_stop = "if test -f %s; then _gdbserver_pid=\\$(cat %s); " % (
            pid_file, pid_file)
        gdbserver_cmd_stop += "kill \\$_gdbserver_pid 2>/dev/null; "
        gdbserver_cmd_stop += self._target_wait_for_process_exit_cmd(
            "gdbserver_pid")
        gdbserver_cmd_stop += " fi; rm -rf %s" % self._gdbserver_tmp_dir(server_mode)
        return "\"/bin/sh -c '" + gdbserver_cmd_stop + "'\""

    def _gen_gdbserver_start_script(self, server_mode=None):
        """Generate a shell script starting the gdbserver on the remote device via ssh"""
        if server_mode is None:
            server_mode = self.default_mode
        gdbserver_cmd_start = self._target_start_cmd(server_mode)
        gdbserver_cmd_stop = self._target_gdbserver_stop_cmd(server_mode)
        remote_ssh = "%s %s" % (self.debugger_cross.target_device.ssh_sshexec,
                                " ".join(self._target_ssh_args()))
        gdbserver_cmd = ['#!/bin/sh']
        gdbserver_cmd.append('if [ "$1" = "stop" ]; then')
        gdbserver_cmd.append('  shift')
        gdbserver_cmd.append("  %s %s" % (remote_ssh, gdbserver_cmd_stop))
        gdbserver_cmd.append('else')
        gdbserver_cmd.append("  %s %s" % (remote_ssh, gdbserver_cmd_start))
        gdbserver_cmd.append('fi')
        GdbCrossConfigNone.write_file(self.server_script(server_mode), gdbserver_cmd, True)

    def _gen_gdbinit_config(self, server_mode=None):
        """Generate a gdbinit file for this binary and the corresponding gdbserver configuration"""
        if server_mode is None:
            server_mode = self.default_mode
        gdbinit_lines = ['# This file is generated by devtool ide-sdk']
        if server_mode == DebuggerServerModes.MULTI:
            target_help = '#   gdbserver --multi :%d' % self.debug_server_port
            remote_cmd = 'target extended-remote'
        else:
            target_help = '#   gdbserver :%d %s' % (
                self.debug_server_port, self.binary)
            remote_cmd = 'target remote'
        gdbinit_lines.append('# On the remote target:')
        gdbinit_lines.append(target_help)
        gdbinit_lines.append('# On the build machine:')
        gdbinit_lines.append('#   cd ' + self.modified_recipe.real_srctree)
        gdbinit_lines.append(
            '#   ' + self.debugger_cross.gdb + ' -ix ' + self.gdbinit)
        gdbinit_lines.append('set sysroot ' + self.modified_recipe.d)

        if self.image_recipe.rootfs_dbg:
            gdbinit_lines.append(
                'set solib-search-path "' + self.modified_recipe.solib_search_path_str(self.image_recipe) + '"')

        gdbinit_lines.append('set substitute-path "/usr/include" "' +
                             os.path.join(self.modified_recipe.recipe_sysroot, 'usr', 'include') + '"')
        if self.image_recipe.rootfs_dbg:
            # First: Search for sources of this recipe in the workspace folder
            # If compiled with DEBUG_PREFIX_MAP = "", no reverse map is is needed. The binaries
            # contain the full path to the source files. But by default there is a reverse map.
            src_file_map = dict(self.modified_recipe.reverse_debug_prefix_map)

            # Second: Search for sources of other recipes in the rootfs-dbg
            # We expect that /usr/src/debug/${PN}/${PV} or no mapping is used for the recipes
            # own sources and we can use the key "/usr/src/debug" for the rootfs-dbg.
            if "/usr/src/debug" in src_file_map:
                logger.error(
                    'Key "/usr/src/debug" already exists in src_file_map. '
                    'Something with DEBUG_PREFIX_MAP looks unexpected and finding sources '
                    'in the rootfs-dbg will not work as expected.'
                )
            else:
                src_file_map["/usr/src/debug"] = os.path.join(
                    self.image_recipe.rootfs_dbg, "usr", "src", "debug")

            for target_path, host_path in src_file_map.items():
                gdbinit_lines.append('set substitute-path "%s" "%s"' % (target_path, host_path))
        else:
            logger.warning(
                "Cannot setup debug symbols configuration for GDB. IMAGE_GEN_DEBUGFS is not enabled.")
        # Disable debuginfod for now, the IDE configuration uses rootfs-dbg from the image workdir.
        gdbinit_lines.append('set debuginfod enabled off')

        # Enable pretty-printing for gdb for resolving STL types with help of python scripts
        pretty_printing_cmd = self.modified_recipe.gdb_pretty_print_scripts
        if pretty_printing_cmd:
            gdbinit_lines.append(os.linesep +"python")
            gdbinit_lines += pretty_printing_cmd
            gdbinit_lines.append("end" + os.linesep)

        gdbinit_lines.append(
            '%s %s:%d' % (remote_cmd, self.debugger_cross.host, self.debug_server_port))
        gdbinit_lines.append('set remote exec-file ' + self.binary.binary_path)
        gdbinit_lines.append('run ' + self.binary.binary_path)

        GdbCrossConfigNone.write_file(self.gdbinit, gdbinit_lines)

    def _gen_gdb_start_script(self):
        """Generate a script starting GDB with the corresponding gdbinit configuration."""
        cmd_lines = ['#!/bin/sh']
        cmd_lines.append('cd ' + self.modified_recipe.real_srctree)
        cmd_lines.append(self.debugger_cross.gdb + ' -ix ' +
                         self.gdbinit + ' "$@"')
        GdbCrossConfigNone.write_file(self.gdb_script, cmd_lines, True)

    def initialize(self):
        self._gen_gdbserver_start_script()
        if self.binary.runs_as_service and self.default_mode != DebuggerServerModes.ATTACH:
            self._gen_gdbserver_start_script(DebuggerServerModes.ATTACH)
        self._gen_gdbinit_config()
        self._gen_gdb_start_script()

    @staticmethod
    def write_file(script_file, cmd_lines, executable=False):
        script_dir = os.path.dirname(script_file)
        mkdirhier(script_dir)
        with open(script_file, 'w') as script_f:
            script_f.write(os.linesep.join(cmd_lines))
            script_f.write(os.linesep)
        if executable:
            st = os.stat(script_file)
            os.chmod(script_file, st.st_mode | stat.S_IEXEC)
        logger.info("Created: %s" % script_file)


class LldbServerConfigNone(LldbServerConfig):
    """Generate lldb helper scripts for ide=none when using the clang toolchain."""

    def __init__(self, image_recipe, modified_recipe, binary,
                 default_mode=DebuggerServerModes.MULTI):
        super().__init__(image_recipe, modified_recipe, binary, default_mode)

    @property
    def lldbinit_dir(self):
        return os.path.join(self.script_dir, 'lldbinit')

    @property
    def lldbinit(self):
        return os.path.join(self.lldbinit_dir, 'lldbinit_' + self.id_pretty)

    @property
    def lldb_script(self):
        return os.path.join(self.script_dir, 'lldb_' + self.id_pretty)

    def _target_lldb_server_stop_cmd(self, server_mode):
        """SSH command to stop lldb-server on the target.

        Stopping is based on the PID file written by the start command. Other
        debug sessions run their own lldb-server on the target, so anything
        matching by process name would hit them as well.
        """
        pid_file = self._lldb_server_pid_file(server_mode)
        tmp_dir = self._lldb_server_tmp_dir(server_mode)
        cmd = "if test -f %s; then _lldb_server_pid=\\$(cat %s); " % (
            pid_file, pid_file)
        cmd += "kill \\$_lldb_server_pid 2>/dev/null; "
        cmd += self._target_wait_for_process_exit_cmd("lldb_server_pid")
        cmd += " fi; rm -rf %s" % tmp_dir
        return "\"/bin/sh -c '" + cmd + "'\""

    def _gen_lldb_server_start_script(self, server_mode=None):
        """Generate a shell script starting lldb-server on the remote device via ssh."""
        if server_mode is None:
            server_mode = self.default_mode
        server_cmd_start = self._target_start_cmd(server_mode)
        server_cmd_stop = self._target_lldb_server_stop_cmd(server_mode)
        remote_ssh = "%s %s" % (self.debugger_cross.target_device.ssh_sshexec,
                                " ".join(self._target_ssh_args()))
        script_lines = ['#!/bin/sh']
        script_lines.append('if [ "$1" = "stop" ]; then')
        script_lines.append('  shift')
        script_lines.append("  %s %s" % (remote_ssh, server_cmd_stop))
        script_lines.append('else')
        script_lines.append("  %s %s" % (remote_ssh, server_cmd_start))
        script_lines.append('fi')
        LldbServerConfigNone.write_file(self.server_script(server_mode), script_lines, True)

    def _gen_lldbinit_config(self, server_mode=None):
        """Generate an lldbinit file for connecting to lldb-server on the target."""
        if server_mode is None:
            server_mode = self.default_mode
        lines = ['# This file is generated by devtool ide-sdk']
        if server_mode == DebuggerServerModes.MULTI:
            lines.append('# On the remote target:')
            lines.append('#   lldb-server platform --server --listen *:%d' % self.debug_server_port)
        else:
            lines.append('# On the remote target:')
            lines.append('#   lldb-server platform --one-shot --server --listen *:%d' % self.debug_server_port)
        lines.append('# On the build machine:')
        lines.append('#   cd ' + self.modified_recipe.real_srctree)
        lines.append('#   ' + self.debugger_cross.lldb + ' -s ' + self.lldbinit)
        lines.append('platform select remote-linux')
        lines.append('platform connect connect://%s:%d' % (
            self.debugger_cross.host, self.debug_server_port))
        lines.append('settings set target.process.thread.step-avoid-regexp ""')

        if self.image_recipe.rootfs_dbg:
            src_file_map = dict(self.modified_recipe.reverse_debug_prefix_map)
            if '/usr/src/debug' in src_file_map:
                logger.error(
                    'Key "/usr/src/debug" already exists in source map. '
                    'Something with DEBUG_PREFIX_MAP looks unexpected and finding '
                    'sources in the rootfs-dbg will not work as expected.')
            else:
                src_file_map['/usr/src/debug'] = os.path.join(
                    self.image_recipe.rootfs_dbg, 'usr', 'src', 'debug')
            if src_file_map:
                # Pass all pairs as a single settings set call
                map_args = []
                for target_path, host_path in src_file_map.items():
                    map_args += ['"' + target_path + '"', '"' + host_path + '"']
                lines.append('settings set target.source-map %s' % ' '.join(map_args))

            debug_search_paths = ' '.join(
                self.modified_recipe.solib_search_path(self.image_recipe))
            lines.append('settings set target.debug-file-search-paths %s' % debug_search_paths)

            exec_paths = list(dict.fromkeys([
                os.path.join(self.modified_recipe.d, self.modified_recipe.libdir.lstrip('/')),
                os.path.join(self.modified_recipe.d, self.modified_recipe.base_libdir.lstrip('/')),
                os.path.join(self.modified_recipe.d, self.modified_recipe.bindir.lstrip('/')),
            ]))
            lines.append('settings set target.exec-search-paths %s' % ' '.join(exec_paths))
        else:
            logger.warning(
                'Cannot setup debug symbols configuration for LLDB. '
                'IMAGE_GEN_DEBUGFS is not enabled.')

        lines.append('target create --remote-file %s %s' % (
            self.binary.binary_path, self.binary.binary_host_path))

        LldbServerConfigNone.write_file(self.lldbinit, lines)

    def _gen_lldb_start_script(self):
        """Generate a script starting lldb with the lldbinit configuration."""
        cmd_lines = ['#!/bin/sh']
        cmd_lines.append('cd ' + self.modified_recipe.real_srctree)
        cmd_lines.append(self.debugger_cross.lldb + ' -s ' + self.lldbinit + ' "$@"')
        LldbServerConfigNone.write_file(self.lldb_script, cmd_lines, True)

    def initialize(self):
        self._gen_lldb_server_start_script()
        self._gen_lldbinit_config()
        self._gen_lldb_start_script()

    @staticmethod
    def write_file(script_file, cmd_lines, executable=False):
        script_dir = os.path.dirname(script_file)
        mkdirhier(script_dir)
        with open(script_file, 'w') as script_f:
            script_f.write(os.linesep.join(cmd_lines))
            script_f.write(os.linesep)
        if executable:
            st = os.stat(script_file)
            os.chmod(script_file, st.st_mode | stat.S_IEXEC)
        logger.info("Created: %s" % script_file)


class IdeNone(IdeBase):
    """Generate some generic helpers for other IDEs

    Modified recipe mode:
    Generate some helper scripts for remote debugging with GDB

    Shared sysroot mode:
    A wrapper for bitbake meta-ide-support and bitbake build-sysroots
    """

    def __init__(self):
        super().__init__()

    def setup_shared_sysroots(self, shared_env):
        real_multimach_target_sys = shared_env.ide_support.real_multimach_target_sys
        deploy_dir_image = shared_env.ide_support.deploy_dir_image
        env_script = os.path.join(
            deploy_dir_image, 'environment-setup-' + real_multimach_target_sys)
        logger.info(
            "To use this SDK please source this: %s" % env_script)

    def setup_modified_recipe(self, args, image_recipe, modified_recipe):
        """generate some helper scripts and config files

        - Execute the do_install task
        - Execute devtool deploy-target
        - Generate a gdbinit file per executable
        - Generate the oe-scripts sym-link
        """
        script_path = modified_recipe.gen_install_deploy_script(args)
        logger.info("Created: %s" % script_path)

        if modified_recipe.toolchain == 'clang':
            self.initialize_cross_debug_configs(
                image_recipe, modified_recipe, LldbServerConfigNone)
        else:
            self.initialize_cross_debug_configs(
                image_recipe, modified_recipe, GdbCrossConfigNone)

        IdeBase.gen_oe_scripts_sym_link(modified_recipe)


def register_ide_plugin(ide_plugins):
    ide_plugins['none'] = IdeNone
