#
# Copyright (C) 2023-2024 Siemens AG
#
# SPDX-License-Identifier: GPL-2.0-only
#
"""Devtool ide-sdk IDE plugin for VSCode and VSCodium"""

import json
import logging
import os
import shutil
from devtool.ide_plugins import BuildTool, IdeBase, GdbCrossConfig, DebuggerServerModes, LldbServerConfig, get_devtool_deploy_opts

logger = logging.getLogger('devtool')


class GdbCrossConfigVSCode(GdbCrossConfig):
    def __init__(self, image_recipe, modified_recipe, binary,
                 default_mode=DebuggerServerModes.ONCE):
        super().__init__(image_recipe, modified_recipe, binary,
                         default_mode)

    def target_ssh_gdbserver_start_args(self, mode=None):
        """Get the ssh command arguments to start gdbserver on the target device

        returns something like:
          ['-p', '2222', 'root@target', '"/bin/sh -c \'/usr/bin/gdbserver --once :1234 /usr/bin/cmake-example\'"']
        """
        if mode is None:
            mode = self.default_mode
        return self._target_ssh_args() + [
            self._target_start_cmd(mode)
        ]

    def target_ssh_gdbserver_kill_args(self):
        """Get the ssh command arguments to kill gdbserver on the target device

        returns something like:
          ['-p', '2222', 'root@target', '"kill $(pgrep -o -f \'gdbserver --attach :1234\') 2>/dev/null || true"']
        """
        return self._target_ssh_args() + [
            self._target_kill_cmd()
        ]


class LldbServerConfigVSCode(LldbServerConfig):
    """VSCode-specific lldb-server configuration for CodeLLDB remote debugging."""

    def __init__(self, image_recipe, modified_recipe, binary,
                 default_mode=DebuggerServerModes.MULTI):
        super().__init__(image_recipe, modified_recipe, binary,
                         default_mode)

    def target_ssh_gdbserver_start_args(self, mode=None):
        """SSH argument list to start lldb-server on the target"""
        if mode is None:
            mode = self.default_mode
        return self._target_ssh_args() + [
            self._target_start_cmd(mode)
        ]

    def target_ssh_gdbserver_kill_args(self):
        """SSH argument list to stop a running MULTI-mode lldb-server"""
        return self._target_ssh_args() + [
            self._target_kill_cmd()
        ]

class IdeVSCode(IdeBase):
    """Manage IDE configurations for VSCode

    Modified recipe mode:
    - cmake: use the cmake-preset generated by devtool ide-sdk
    - meson: meson is called via a wrapper script generated by devtool ide-sdk

    Shared sysroot mode:
    In shared sysroot mode, the cross tool-chain is exported to the user's global configuration.
    A workspace cannot be created because there is no recipe that defines how a workspace could
    be set up.
    - cmake: adds a cmake-kit to .local/share/CMakeTools/cmake-tools-kits.json
             The cmake-kit uses the environment script and the tool-chain file
             generated by meta-ide-support.
    - meson: Meson needs manual workspace configuration.
    """

    @classmethod
    def ide_plugin_priority(cls):
        """If --ide is not passed this is the default plugin"""
        if shutil.which('code'):
            return 100
        return 0

    def setup_shared_sysroots(self, shared_env):
        """Expose the toolchain of the shared sysroots SDK"""
        datadir = shared_env.ide_support.datadir
        deploy_dir_image = shared_env.ide_support.deploy_dir_image
        real_multimach_target_sys = shared_env.ide_support.real_multimach_target_sys
        standalone_sysroot_native = shared_env.build_sysroots.standalone_sysroot_native
        vscode_ws_path = os.path.join(
            os.environ['HOME'], '.local', 'share', 'CMakeTools')
        cmake_kits_path = os.path.join(vscode_ws_path, 'cmake-tools-kits.json')
        oecmake_generator = "Ninja"
        env_script = os.path.join(
            deploy_dir_image, 'environment-setup-' + real_multimach_target_sys)

        if not os.path.isdir(vscode_ws_path):
            os.makedirs(vscode_ws_path)
        cmake_kits_old = []
        if os.path.exists(cmake_kits_path):
            with open(cmake_kits_path, 'r', encoding='utf-8') as cmake_kits_file:
                cmake_kits_old = json.load(cmake_kits_file)
        cmake_kits = cmake_kits_old.copy()

        cmake_kit_new = {
            "name": "OE " + real_multimach_target_sys,
            "environmentSetupScript": env_script,
            "toolchainFile": standalone_sysroot_native + datadir + "/cmake/OEToolchainConfig.cmake",
            "preferredGenerator": {
                "name": oecmake_generator
            }
        }

        def merge_kit(cmake_kits, cmake_kit_new):
            i = 0
            while i < len(cmake_kits):
                if 'environmentSetupScript' in cmake_kits[i] and \
                        cmake_kits[i]['environmentSetupScript'] == cmake_kit_new['environmentSetupScript']:
                    cmake_kits[i] = cmake_kit_new
                    return
                i += 1
            cmake_kits.append(cmake_kit_new)
        merge_kit(cmake_kits, cmake_kit_new)

        if cmake_kits != cmake_kits_old:
            logger.info("Updating: %s" % cmake_kits_path)
            with open(cmake_kits_path, 'w', encoding='utf-8') as cmake_kits_file:
                json.dump(cmake_kits, cmake_kits_file, indent=4)
        else:
            logger.info("Already up to date: %s" % cmake_kits_path)

        cmake_native = os.path.join(
            shared_env.build_sysroots.standalone_sysroot_native, 'usr', 'bin', 'cmake')
        if os.path.isfile(cmake_native):
            logger.info('cmake-kits call cmake by default. If the cmake provided by this SDK should be used, please add the following line to ".vscode/settings.json" file: "cmake.cmakePath": "%s"' % cmake_native)
        else:
            logger.error("Cannot find cmake native at: %s" % cmake_native)

    def dot_code_dir(self, modified_recipe):
        return os.path.join(modified_recipe.srctree, '.vscode')

    def __gen_meson_absolute_cross_file(self, modified_recipe):
        """Generate an extra cross file overriding c/cpp binaries with absolute paths.

        The recipe's generated meson.cross references the toolchain binaries
        (e.g. "aarch64-poky-linux-clang++") by bare name, relying on PATH
        being set up by the meson wrapper script at build time. Meson stores
        that command exactly as configured (it never resolves it to an
        absolute path itself), so it ends up unresolved in
        compile_commands.json and meson-info/intro-compilers.json. cpptools
        (via the mesonbuild extension) resolves compilerPath using its own
        process PATH, which does not include the toolchain directory, and
        silently falls back to a host compiler for IntelliSense.

        Real builds are unaffected since the wrapper script sets up PATH, so
        the recipe's meson.cross is left untouched. Instead, an extra
        --cross-file is layered on top with only the c/cpp [binaries]
        entries absolutized, reusing the exact same flags as CC/CXX to avoid
        any behavior drift. Meson merges multiple machine files, with later
        files overriding matching keys from earlier ones.
        """
        def absolutize(cmd):
            args = cmd.split()
            args[0] = os.path.join(
                modified_recipe.staging_bindir_toolchain, args[0])
            return repr(args)

        lines = ["[binaries]"]
        if modified_recipe.cc:
            lines.append("c = %s" % absolutize(modified_recipe.cc))
        if modified_recipe.cxx:
            lines.append("cpp = %s" % absolutize(modified_recipe.cxx))

        os.makedirs(modified_recipe.ide_sdk_dir, exist_ok=True)
        cross_file = os.path.join(
            modified_recipe.ide_sdk_dir, 'meson-absolute-toolchain.cross')
        with open(cross_file, 'w') as f:
            f.write(os.linesep.join(lines) + os.linesep)
        return ['--cross-file', cross_file]

    def __vscode_settings_meson(self, settings_dict, modified_recipe):
        if modified_recipe.build_tool is not BuildTool.MESON:
            return
        settings_dict["mesonbuild.mesonPath"] = modified_recipe.meson_wrapper

        confopts = modified_recipe.mesonopts.split()
        confopts += modified_recipe.meson_cross_file.split()
        if modified_recipe.meson_cross_file:
            confopts += self.__gen_meson_absolute_cross_file(modified_recipe)
        confopts += modified_recipe.extra_oemeson.split()
        settings_dict["mesonbuild.configureOptions"] = confopts
        settings_dict["mesonbuild.buildFolder"] = modified_recipe.b

    def __vscode_settings_cmake(self, settings_dict, modified_recipe):
        """Add cmake specific settings to settings.json.

        Note: most settings are passed to the cmake preset.
        """
        if modified_recipe.build_tool is not BuildTool.CMAKE:
            return
        settings_dict["cmake.configureOnOpen"] = True
        settings_dict["cmake.sourceDirectory"] = modified_recipe.real_srctree

    def __vscode_settings_kernel_module(self, settings_dict, modified_recipe):
        if modified_recipe.build_tool is not BuildTool.KERNEL_MODULE:
            return

        # Define kernel exclude patterns once
        kernel_exclude_patterns = [
            "*.cache/**",
            "*.ko",
            "*.mod.c",
            "*.mod",
            "**/.*.cmd",
            "**/.*.d",
            "**/.*.S",
            "**/.tmp*",
            "**/*.a",
            "**/*.builtin",
            "**/*.map",
            "**/*.modinfo",
            "**/*.o",
            "**/*.order",
            "**/*.orig",
            "**/*.symvers",
            "**/*.tmp"
        ]
        files_excludes_kernel = {pattern: True for pattern in kernel_exclude_patterns}

        settings_dict["files.exclude"].update(files_excludes_kernel)
        settings_dict["files.watcherExclude"].update(files_excludes_kernel)
        settings_dict["python.analysis.exclude"] += kernel_exclude_patterns

        # protect the kernel sources
        settings_dict["files.readonlyInclude"][modified_recipe.staging_kernel_dir + '/**'] = True

        # Export the complete cross-build environment
        settings_dict["terminal.integrated.env.linux"] = modified_recipe.exported_vars

        # and the make configuration
        make_executable = os.path.join(
            modified_recipe.recipe_sysroot_native, 'usr', 'bin', 'make')
        settings_dict["makefile.configurations"] = [
            {
                "name": ' '.join(modified_recipe.make_targets),
                "makePath": make_executable,
                "makeDirectory": modified_recipe.srctree,
                "makefilePath": os.path.join(modified_recipe.srctree, "Makefile"),
                "makeArgs": modified_recipe.extra_oemake + modified_recipe.make_targets
            },
            {
                "name": "clean",
                "makePath": make_executable,
                "makeDirectory": modified_recipe.srctree,
                "makefilePath": os.path.join(modified_recipe.srctree, "Makefile"),
                "makeArgs": modified_recipe.extra_oemake + ["clean"]
            }
        ]

    def vscode_settings(self, modified_recipe, image_recipe):
        files_excludes = {
            "**/.git/**": True,
            "**/oe-logs/**": True,
            "**/oe-workdir/**": True,
            "**/source-date-epoch/**": True
        }
        python_exclude = [
            "**/.git/**",
            "**/oe-logs/**",
            "**/oe-workdir/**",
            "**/source-date-epoch/**"
        ]
        files_readonly = {
            modified_recipe.recipe_sysroot + '/**': True,
            modified_recipe.recipe_sysroot_native + '/**': True,
        }
        if image_recipe.rootfs_dbg is not None:
            files_readonly[image_recipe.rootfs_dbg + '/**'] = True
        settings_dict = {
            "files.watcherExclude": files_excludes,
            "files.exclude": files_excludes,
            "files.readonlyInclude": files_readonly,
            "python.analysis.exclude": python_exclude
        }
        self.__vscode_settings_cmake(settings_dict, modified_recipe)
        self.__vscode_settings_meson(settings_dict, modified_recipe)
        self.__vscode_settings_kernel_module(settings_dict, modified_recipe)

        settings_file = 'settings.json'
        IdeBase.update_json_file(
            self.dot_code_dir(modified_recipe), settings_file, settings_dict)

    def vscode_extensions(self, modified_recipe):
        recommendations = []
        if modified_recipe.build_tool.is_c_cpp_kernel:
            recommendations += [
                "ms-vscode.cpptools",
                "ms-vscode.cpptools-extension-pack",
                "ms-vscode.cpptools-themes"
            ]
        # For clang toolchain, CodeLLDB provides native LLDB debugging in VSCode
        if (modified_recipe.toolchain == 'clang'
                and modified_recipe.build_tool.is_c_cpp):
            recommendations.append("vadimcn.vscode-lldb")
        if modified_recipe.build_tool is BuildTool.CMAKE:
            recommendations.append("ms-vscode.cmake-tools")
        if modified_recipe.build_tool is BuildTool.MESON:
            recommendations.append("mesonbuild.mesonbuild")
        if modified_recipe.build_tool is BuildTool.KERNEL_MODULE:
            recommendations.append("ms-vscode.makefile-tools")

        extensions_file = 'extensions.json'
        IdeBase.update_json_file(
            self.dot_code_dir(modified_recipe), extensions_file, {"recommendations": recommendations})

    def vscode_c_cpp_properties(self, modified_recipe):
        properties_dict = {
            "name": modified_recipe.recipe_id_pretty,
        }
        if modified_recipe.build_tool is BuildTool.CMAKE:
            properties_dict["configurationProvider"] = "ms-vscode.cmake-tools"
        elif modified_recipe.build_tool is BuildTool.MESON:
            properties_dict["configurationProvider"] = "mesonbuild.mesonbuild"
            properties_dict["compilerPath"] = os.path.join(modified_recipe.staging_bindir_toolchain, modified_recipe.cxx.split()[0])
        elif modified_recipe.build_tool is BuildTool.KERNEL_MODULE:
            # Using e.g. configurationProvider = "ms-vscode.makefile-tools" was not successful
            properties_dict["compilerPath"] = os.path.join(modified_recipe.staging_bindir_toolchain, modified_recipe.kernel_cc.split()[0])
            properties_dict["includePath"] = [
                "${workspaceFolder}/**",
                os.path.join(modified_recipe.staging_kernel_dir, "include", "**")
            ]
            # https://www.kernel.org/doc/html/next/process/programming-language.html
            properties_dict["cStandard"] = "gnu11"
        else:  # no C/C++ build
            return

        properties_dicts = {
            "configurations": [
                properties_dict
            ],
            "version": 4
        }
        prop_file = 'c_cpp_properties.json'
        IdeBase.update_json_file(
            self.dot_code_dir(modified_recipe), prop_file, properties_dicts)

    def vscode_launch_bin_dbg(self, cross_debug_config, server_mode):
        """Dispatch to the GDB or LLDB launch config generator."""
        if isinstance(cross_debug_config, LldbServerConfig):
            return self._vscode_launch_bin_dbg_lldb(cross_debug_config, server_mode)
        return self._vscode_launch_bin_dbg_gdb(cross_debug_config, server_mode)

    def _vscode_launch_bin_dbg_gdb(self, cross_debug_config, server_mode):
        """Generate a cppdbg (GDB) launch configuration entry for launch.json."""
        modified_recipe = cross_debug_config.modified_recipe

        launch_config = {
            "name": cross_debug_config.id_pretty_mode(server_mode),
            "type": "cppdbg",
            "request": "launch",
            "program": cross_debug_config.binary.binary_host_path,
            "stopAtEntry": True,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": False,
            "MIMode": "gdb",
            "preLaunchTask": cross_debug_config.id_pretty_mode(server_mode),
            "miDebuggerPath": modified_recipe.debugger_cross.gdb,
            "miDebuggerServerAddress": "%s:%d" % (modified_recipe.debugger_cross.host, cross_debug_config.debug_server_port)
        }

        # Search for header files in recipe-sysroot.
        src_file_map = {
            "/usr/include": os.path.join(modified_recipe.recipe_sysroot, "usr", "include")
        }
        # First of all search for not stripped binaries in the image folder.
        # These binaries are copied (and optionally stripped) by deploy-target
        setup_commands = [
            {
                "description": "sysroot",
                "text": "set sysroot " + modified_recipe.d
            }
        ]

        if cross_debug_config.image_recipe.rootfs_dbg:
            launch_config['additionalSOLibSearchPath'] = modified_recipe.solib_search_path_str(
                cross_debug_config.image_recipe)
            # First: Search for sources of this recipe in the workspace folder
            # If compiled with DEBUG_PREFIX_MAP = "", no reverse map is is needed. The binaries
            # contain the full path to the source files. But by default there is a reverse map.
            for target_path, host_path in modified_recipe.reverse_debug_prefix_map.items():
                if host_path.startswith(modified_recipe.real_srctree):
                    src_file_map[target_path] = "${workspaceFolder}" + host_path[len(modified_recipe.real_srctree):]
                else:
                    src_file_map[target_path] = host_path

            # Second: Search for sources of other recipes in the rootfs-dbg
            # We expect that /usr/src/debug/${PN}/${PV} or no mapping is used for the recipes
            # own sources and we can use the key "/usr/src/debug" for the rootfs-dbg.
            if "/usr/src/debug" in src_file_map:
                logger.error(
                    'Key "/usr/src/debug" already exists in src_file_map. '
                    'Something with DEBUG_PREFIX_MAP looks unexpected and finding '
                    'sources in the rootfs-dbg will not work as expected.'
                )
            else:
                src_file_map["/usr/src/debug"] = os.path.join(
                    cross_debug_config.image_recipe.rootfs_dbg, "usr", "src", "debug")
        else:
            logger.warning(
                "Cannot setup debug symbols configuration for GDB. IMAGE_GEN_DEBUGFS is not enabled.")

        # Enable pretty-printing for gdb for resolving STL types with help of python scripts
        pretty_printing_cmd = modified_recipe.gdb_pretty_print_scripts
        if pretty_printing_cmd:
            setup_commands += [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "python " +";".join(pretty_printing_cmd)
                },
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing"
                }
            ]

        launch_config['sourceFileMap'] = src_file_map
        launch_config['setupCommands'] = setup_commands

        # Add postDebugTask for attach mode to clean up gdbserver
        if server_mode == DebuggerServerModes.ATTACH:
            kill_task_label = "kill_gdbserver_" + cross_debug_config.id_pretty_mode(server_mode)
            launch_config["postDebugTask"] = kill_task_label

        return launch_config

    def _vscode_launch_bin_dbg_lldb(self, lldb_config, server_mode):
        """Generate a CodeLLDB (type: lldb) launch configuration entry for launch.json.

        CodeLLDB connects to lldb-server via the LLDB platform protocol.  The
        initCommands select the remote platform and open the connection before
        the process is launched, so CodeLLDB can inspect and control it.

        Using targetCreateCommands instead of "program" so we can pass both the
        local host binary (for debug symbols) and the remote target path (where
        devtool deploy-target has already installed the binary) to
        "target create --remote-file".  This prevents LLDB from uploading the
        binary from its module cache to a temporary directory and ensures the
        process starts from its installed location where the dynamic linker can
        find shared libraries via the standard search paths.
        """
        modified_recipe = lldb_config.modified_recipe
        debugger_cross = modified_recipe.debugger_cross

        init_commands = [
            "platform select remote-linux",
            "platform connect connect://%s:%d" % (debugger_cross.host, lldb_config.debug_server_port),
            # Clear the default step-avoid-regexp so std:: and other library
            # namespaces are not silently skipped on step-in. (default is "std::" in LLDB 15+)
            "settings set target.process.thread.step-avoid-regexp \"\"",
        ]
        # Search for header files in recipe-sysroot (same as GDB sourceFileMap).
        source_map = {
            "/usr/include": os.path.join(modified_recipe.recipe_sysroot, "usr", "include")
        }
        if lldb_config.image_recipe.rootfs_dbg:
            # Map build-time paths back to the workspace source tree.
            for target_path, host_path in modified_recipe.reverse_debug_prefix_map.items():
                if host_path.startswith(modified_recipe.real_srctree):
                    source_map[target_path] = (
                        "${workspaceFolder}"
                        + host_path[len(modified_recipe.real_srctree):])
                else:
                    source_map[target_path] = host_path
            if "/usr/src/debug" in source_map:
                logger.error(
                    'Key "/usr/src/debug" already exists in source_map. '
                    'Something with DEBUG_PREFIX_MAP looks unexpected and finding '
                    'sources in the rootfs-dbg will not work as expected.')
            else:
                source_map["/usr/src/debug"] = os.path.join(
                    lldb_config.image_recipe.rootfs_dbg, "usr", "src", "debug")

            # Point LLDB at the .debug directories in rootfs-dbg.
            debug_search_paths = " ".join(
                modified_recipe.solib_search_path(lldb_config.image_recipe))
            init_commands.append(
                "settings set target.debug-file-search-paths %s" % debug_search_paths)

            # Point LLDB at the unstripped binaries and shared libraries in ${D}
            # so it can load debug symbols for the recipe's own shared libraries.
            # These are the files deployed by devtool deploy-target.
            exec_search_paths = " ".join([
                os.path.join(modified_recipe.d, modified_recipe.libdir.lstrip('/')),
                os.path.join(modified_recipe.d, modified_recipe.base_libdir.lstrip('/')),
                os.path.join(modified_recipe.d, modified_recipe.bindir.lstrip('/')),
            ])
            # Deduplicate in case base_libdir == libdir or paths coincide
            exec_search_paths = " ".join(dict.fromkeys(exec_search_paths.split()))
            init_commands.append(
                "settings set target.exec-search-paths %s" % exec_search_paths)
        else:
            logger.warning(
                "Cannot setup debug symbols configuration for LLDB. "
                "IMAGE_GEN_DEBUGFS is not enabled.")

        # "target create --remote-file <target_path> <host_debug_binary>":
        # --remote-file tells LLDB which path to execute on the target.
        # The positional argument is the local host binary, loaded for symbols.
        # This keeps devtool deploy-target as the sole deployment mechanism and
        # avoids LLDB uploading the binary to a temporary directory via its
        # module cache.  Running from the installed path ensures the dynamic
        # linker on the target can find shared libraries at their standard
        # locations.
        target_create_cmd = "target create --remote-file %s %s" % (
            lldb_config.binary.binary_path,
            lldb_config.binary.binary_host_path)

        launch_config = {
            "name": lldb_config.id_pretty_mode(server_mode),
            "type": "lldb",
            "request": "launch",
            # Use targetCreateCommands instead of "program" to control both
            # the local binary (for debug symbols) and the remote path.
            "targetCreateCommands": [target_create_cmd],
            "stopOnEntry": False,
            "cwd": "/tmp",
            "preLaunchTask": lldb_config.id_pretty_mode(server_mode),
            "initCommands": init_commands,
        }
        if source_map:
            launch_config["sourceMap"] = source_map
        if modified_recipe.b:
            # CodeLLDB resolves any source path that is still relative (as
            # opposed to being rewritten to an absolute path by sourceMap /
            # target.source-map) against "relativePathBase", defaulting to
            # ${workspaceFolder}. Compilers are invoked with the build
            # directory B as their working directory, so relative DW_AT_name
            # entries (e.g. from meson/ninja) are relative to B. Pointing
            # relativePathBase at B lets CodeLLDB resolve these directly,
            # which matters in particular for devtool workspaces where S
            # (and thus ${workspaceFolder}) is relocated outside of WORKDIR.
            launch_config["relativePathBase"] = modified_recipe.b

        return launch_config

    def vscode_launch(self, args, modified_recipe):
        """GDB launch configurations for user-space binaries.

        Kernel modules are not debugged via gdbserver and have no launch entry.
        Their deployment workflow is driven entirely by tasks.json:
          install && deploy-target  ->  reload module (rmmod + insmod)  ->  verify module
        These tasks can be triggered from the Tasks menu (Ctrl+Shift+P > Run Task)
        or via the default build task (Ctrl+Shift+B for install && deploy-target).
        """

        configurations = []
        for cross_debug_config in self.cross_debug_configs:
            if cross_debug_config.modified_recipe is modified_recipe:
                for server_mode in cross_debug_config.server_modes():
                    configurations.append(self.vscode_launch_bin_dbg(cross_debug_config, server_mode))
        launch_dict = {
            "version": "0.2.0",
            "configurations": configurations
        }
        launch_file = 'launch.json'
        IdeBase.update_json_file(
            self.dot_code_dir(modified_recipe), launch_file, launch_dict)

    def vscode_tasks_cpp(self, args, modified_recipe):
        run_install_deploy = modified_recipe.gen_install_deploy_script(args)
        install_task_name = "install && deploy-target %s" % modified_recipe.recipe_id_pretty
        tasks_dict = {
            "version": "2.0.0",
            "tasks": [
                {
                    "label": install_task_name,
                    "type": "shell",
                    "command": run_install_deploy,
                    "args": ["--target", args.target] + (["--port", args.port] if args.port else []),
                    "problemMatcher": []
                }
            ]
        }
        for cross_debug_config in self.cross_debug_configs:
            if cross_debug_config.modified_recipe is not modified_recipe:
                continue
            for server_mode in cross_debug_config.server_modes():
                if server_mode == DebuggerServerModes.MULTI:
                    # MULTI mode: the SSH command blocks until the port is ready
                    # (wait loop in _target_start_cmd), so VSCode treats this as
                    # a regular non-background task.
                    new_task = {
                        "label": cross_debug_config.id_pretty_mode(server_mode),
                        "type": "shell",
                        "command": cross_debug_config.debugger_cross.target_device.ssh_sshexec,
                        "args": cross_debug_config.target_ssh_gdbserver_start_args(server_mode),
                        "problemMatcher": []
                    }
                else:
                    # ONCE / ATTACH: gdbserver runs in the foreground for the
                    # whole session, so VSCode needs isBackground + a pattern
                    # matcher to avoid waiting for the task to exit.
                    new_task = {
                        "label": cross_debug_config.id_pretty_mode(server_mode),
                        "type": "shell",
                        "isBackground": True,
                        "command": cross_debug_config.debugger_cross.target_device.ssh_sshexec,
                        "args": cross_debug_config.target_ssh_gdbserver_start_args(server_mode),
                        "problemMatcher": [
                            {
                                "pattern": [
                                    {
                                        "regexp": ".",
                                        "file": 1,
                                        "location": 2,
                                        "message": 3
                                    }
                                ],
                                "background": {
                                    "activeOnStart": True,
                                    "beginsPattern": ".",
                                    "endsPattern": ".",
                                }
                            }
                        ]
                    }
                # Deploy the artifacts to the target before starting gdbserver if not already running
                if server_mode != DebuggerServerModes.ATTACH:
                    new_task['dependsOn'] = [
                        install_task_name
                    ]

                tasks_dict['tasks'].append(new_task)

                # For attach mode, add a kill task to stop a previously running gdbserver
                # This is a known issue with gdbserver --attach that it does not terminate
                # after detaching. With this helper task, it is possible to:
                # 1. Start debugging in attach mode
                # 2. Add breakpoints, step, continue, etc.
                # 3. Press the Continue button
                # 4. Press the Stop button which detaches gdbserver from the debugged process
                # 5. Start debugging again in attach mode
                # Without this kill task, step 5 would fail because gdbserver is still running
                if server_mode == DebuggerServerModes.ATTACH:
                    new_task_kill_label = "kill_gdbserver_"+ cross_debug_config.id_pretty_mode(server_mode)
                    new_task_kill = {
                        "label": new_task_kill_label,
                        "type": "shell",
                        "command": cross_debug_config.debugger_cross.target_device.ssh_sshexec,
                        "args": cross_debug_config.target_ssh_gdbserver_kill_args(),
                        "presentation": {
                            "close": True
                        },
                        "problemMatcher": []
                    }
                    tasks_dict['tasks'].append(new_task_kill)

        tasks_file = 'tasks.json'
        IdeBase.update_json_file(
            self.dot_code_dir(modified_recipe), tasks_file, tasks_dict)

    @staticmethod
    def _ssh_args(target_device, remote_cmd):
        """Build a VS Code task 'args' list for an ssh command to the target."""
        args = list(target_device.extraoptions)
        if target_device.ssh_port:
            args += list(target_device.ssh_port)
        args += [target_device.target, remote_cmd]
        return args

    def vscode_tasks_kernel_module(self, args, modified_recipe):
        """Generate tasks.json for kernel module recipes.

        Three tasks are generated and chained in sequence:
          1. install && deploy-target  - run bitbake do_install and push the
             freshly built .ko to the target via devtool deploy-target.
          2. reload module  - single SSH call: rmmod (errors ignored) then insmod
             using the path reported by find so depmod is not required.
          3. verify module  - SSH call: lsmod | grep <module> to confirm the new
             module is loaded; output is visible in the task terminal.

        The tasks are linked via dependsOn / dependsOrder: sequence so that
        running the verify task automatically executes the full chain.  The
        launch.json 'reload kernel module' entry uses preLaunchTask: verify,
        providing a single F5 / click action for the complete reload cycle.
        """
        td = modified_recipe.debugger_cross.target_device
        ko_name = modified_recipe.bpn + '.ko'
        # rmmod / lsmod use the kernel module name (- replaced by _ per kernel convention)
        mod_name = modified_recipe.bpn.replace('-', '_')
        install_task_name = "install && deploy-target %s" % modified_recipe.recipe_id_pretty
        reload_task_name = "reload module %s" % modified_recipe.recipe_id_pretty
        verify_task_name = "verify module %s" % modified_recipe.recipe_id_pretty
        run_install_deploy = modified_recipe.gen_install_deploy_script(args)
        tasks_dict = {
            "version": "2.0.0",
            "tasks": [
                {
                    "label": install_task_name,
                    "type": "shell",
                    "command": run_install_deploy,
                    "args": ["--target", args.target] + (["--port", args.port] if args.port else []),
                    "problemMatcher": []
                },
                {
                    "label": reload_task_name,
                    "type": "shell",
                    "command": td.ssh_sshexec,
                    "args": self._ssh_args(
                        td,
                        "rmmod %(mod)s 2>/dev/null; insmod $(find /lib/modules -name '%(ko)s' | head -n 1)"
                        % {"mod": mod_name, "ko": ko_name}),
                    "dependsOn": [install_task_name],
                    "dependsOrder": "sequence",
                    "problemMatcher": []
                },
                {
                    "label": verify_task_name,
                    "type": "shell",
                    "command": td.ssh_sshexec,
                    "args": self._ssh_args(td, "lsmod | grep %s" % mod_name),
                    "dependsOn": [reload_task_name],
                    "dependsOrder": "sequence",
                    "problemMatcher": []
                }
            ]
        }
        tasks_file = 'tasks.json'
        IdeBase.update_json_file(
            self.dot_code_dir(modified_recipe), tasks_file, tasks_dict)

    def vscode_tasks_fallback(self, args, modified_recipe):
        oe_init_dir = modified_recipe.oe_init_dir
        oe_init = ". %s %s > /dev/null && " % (modified_recipe.oe_init_build_env, modified_recipe.topdir)
        dt_build = "devtool build "
        dt_build_label = dt_build + modified_recipe.recipe_id_pretty
        dt_build_cmd = dt_build + modified_recipe.bpn
        clean_opt = " --clean"
        dt_build_clean_label = dt_build + modified_recipe.recipe_id_pretty + clean_opt
        dt_build_clean_cmd = dt_build + modified_recipe.bpn + clean_opt
        dt_deploy = "devtool deploy-target "
        dt_deploy_label = dt_deploy + modified_recipe.recipe_id_pretty
        dt_deploy_cmd = dt_deploy + modified_recipe.bpn
        dt_build_deploy_label = "devtool build & deploy-target %s" % modified_recipe.recipe_id_pretty
        deploy_opts = ' '.join(get_devtool_deploy_opts(args))
        tasks_dict = {
            "version": "2.0.0",
            "tasks": [
                {
                    "label": dt_build_label,
                    "type": "shell",
                    "command": "bash",
                    "linux": {
                        "options": {
                            "cwd": oe_init_dir
                        }
                    },
                    "args": [
                        "--login",
                        "-c",
                        "%s%s" % (oe_init, dt_build_cmd)
                    ],
                    "problemMatcher": []
                },
                {
                    "label": dt_deploy_label,
                    "type": "shell",
                    "command": "bash",
                    "linux": {
                        "options": {
                            "cwd": oe_init_dir
                        }
                    },
                    "args": [
                        "--login",
                        "-c",
                        "%s%s %s" % (
                            oe_init, dt_deploy_cmd, deploy_opts)
                    ],
                    "problemMatcher": []
                },
                {
                    "label": dt_build_deploy_label,
                    "dependsOrder": "sequence",
                    "dependsOn": [
                        dt_build_label,
                        dt_deploy_label
                    ],
                    "problemMatcher": [],
                    "group": {
                        "kind": "build",
                        "isDefault": True
                    }
                },
                {
                    "label": dt_build_clean_label,
                    "type": "shell",
                    "command": "bash",
                    "linux": {
                        "options": {
                            "cwd": oe_init_dir
                        }
                    },
                    "args": [
                        "--login",
                        "-c",
                        "%s%s" % (oe_init, dt_build_clean_cmd)
                    ],
                    "problemMatcher": []
                }
            ]
        }
        if modified_recipe.debugger_cross:
            for cross_debug_config in self.cross_debug_configs:
                if cross_debug_config.modified_recipe is not modified_recipe:
                    continue
                for server_mode in cross_debug_config.server_modes():
                    if server_mode == DebuggerServerModes.MULTI:
                        # MULTI mode: SSH command blocks until port is ready, treat as
                        # a regular non-background task (same as vscode_tasks_cpp).
                        new_task = {
                            "label": cross_debug_config.id_pretty_mode(server_mode),
                            "type": "shell",
                            "command": cross_debug_config.debugger_cross.target_device.ssh_sshexec,
                            "args": cross_debug_config.target_ssh_gdbserver_start_args(server_mode),
                            "problemMatcher": []
                        }
                    else:
                        # ONCE / ATTACH: server runs for the whole session, needs
                        # isBackground so VSCode does not wait for the task to exit.
                        new_task = {
                            "label": cross_debug_config.id_pretty_mode(server_mode),
                            "type": "shell",
                            "isBackground": True,
                            "command": cross_debug_config.debugger_cross.target_device.ssh_sshexec,
                            "args": cross_debug_config.target_ssh_gdbserver_start_args(server_mode),
                            "problemMatcher": [
                                {
                                    "pattern": [
                                        {
                                            "regexp": ".",
                                            "file": 1,
                                            "location": 2,
                                            "message": 3
                                        }
                                    ],
                                    "background": {
                                        "activeOnStart": True,
                                        "beginsPattern": ".",
                                        "endsPattern": ".",
                                    }
                                }
                            ]
                        }
                    if server_mode != DebuggerServerModes.ATTACH:
                        new_task['dependsOn'] = [
                            dt_build_deploy_label
                        ]
                    tasks_dict['tasks'].append(new_task)
        tasks_file = 'tasks.json'
        IdeBase.update_json_file(
            self.dot_code_dir(modified_recipe), tasks_file, tasks_dict)

    def vscode_tasks(self, args, modified_recipe):
        if modified_recipe.build_tool.is_c_cpp:
            self.vscode_tasks_cpp(args, modified_recipe)
        elif modified_recipe.build_tool == BuildTool.KERNEL_MODULE:
            self.vscode_tasks_kernel_module(args, modified_recipe)
        else:
            self.vscode_tasks_fallback(args, modified_recipe)

    def setup_modified_recipe(self, args, image_recipe, modified_recipe):
        self.vscode_settings(modified_recipe, image_recipe)
        self.vscode_extensions(modified_recipe)
        self.vscode_c_cpp_properties(modified_recipe)
        if args.target:
            if modified_recipe.toolchain == 'clang':
                self.initialize_cross_debug_configs(
                    image_recipe, modified_recipe, LldbServerConfigVSCode)
            else:
                self.initialize_cross_debug_configs(
                    image_recipe, modified_recipe, GdbCrossConfigVSCode)
            self.vscode_launch(args, modified_recipe)
            self.vscode_tasks(args, modified_recipe)


def register_ide_plugin(ide_plugins):
    ide_plugins['code'] = IdeVSCode
