Upstream-Status: Inappropriate [configuration]

Index: 0.6.4/Makefile.am
===================================================================
--- 0.6.4.orig/Makefile.am	2007-06-28 12:23:37.000000000 +0100
+++ 0.6.4/Makefile.am	2007-06-28 14:21:23.000000000 +0100
@@ -1,5 +1,3 @@
-SUBDIRS = debian
-
 bin_PROGRAMS = clipboard-manager
 
 INCLUDES = 			\
@@ -21,6 +19,6 @@
 	clipboard.txt \
 	clipboard.sh
 
-servicedir = $(sysconfdir)/osso-af-init
+servicedir = $(sysconfdir)/X11/Xsession.d
 
 service_DATA = clipboard.sh
