#
# Default preferred versions
#
PULSEAUDIOVERSION ?= "0.9.22"
PULSEAUDIOVERSION_arm ?= "0.9.15"
PREFERRED_VERSION_pulseaudio ?= "${PULSEAUDIOVERSION}"

# Force the python versions in one place
PYTHON_BASEVERSION ?= "2.6"
PREFERRED_VERSION_python ?= "2.6.6"
PREFERRED_VERSION_python-native ?= "2.6.6"

# Force the older version of liberation-fonts until we fix the fontforge issue
PREFERRED_VERSION_liberation-fonts ?= "1.04"




