# Preferred Versions:
#
PREFERRED_VERSION_libmatchbox ?= "1.9"
PREFERRED_VERSION_matchbox-theme-sato ?= "0.1"
PREFERRED_VERSION_elfutils ?= "0.89"
PREFERRED_VERSION_hal ?= "0.5.14"
PREFERRED_VERSION_hal-info ?= "20091130"
PREFERRED_VERSION_udev ?= "164"
PREFERRED_VERSION_wpa-supplicant ?= "0.7.3"

PULSEAUDIOVERSION ?= "0.9.21"
PULSEAUDIOVERSION_arm ?= "0.9.15"
PREFERRED_VERSION_pulseaudio ?= "${PULSEAUDIOVERSION}"

# Force the python versions in one place
PYTHON_BASEVERSION ?= "2.6"
PREFERRED_VERSION_python ?= "2.6.6"
PREFERRED_VERSION_python-native ?= "2.6.6"

# Force the older version of liberation-fonts until we fix the fontforge issue
PREFERRED_VERSION_liberation-fonts ?= "1.04"




