# Known good source dates/revisions/tags to use:
#



# Preferred Versions:
#
PREFERRED_VERSION_libmatchbox ?= "1.9"
PREFERRED_VERSION_matchbox-theme-sato ?= "0.1"

PREFERRED_VERSION_glib-2.0 ?= "2.24.1"
PREFERRED_VERSION_glib-2.0-native ?= "2.24.1"
PREFERRED_VERSION_atk ?= "1.24.0"
PREFERRED_VERSION_cairo ?= "1.8.10"
PREFERRED_VERSION_pango ?= "1.28.0"
PREFERRED_VERSION_gtk+ ?= "2.20.1"

PREFERRED_VERSION_librsvg ?= "2.26.3"

PREFERRED_VERSION_gnome-vfs ?= "2.22.0"
PREFERRED_VERSION_libgnomecanvas ?= "2.20.0"

PREFERRED_VERSION_evince ?= "2.20.0"
PREFERRED_VERSION_minimo ?= "0.02+cvs${SRCDATE_minimo}"
PREFERRED_VERSION_oprofile ?= "0.9.4"
PREFERRED_VERSION_elfutils ?= "0.89"
PREFERRED_VERSION_hal ?= "0.5.13"
PREFERRED_VERSION_hal-info ?= "20090414"
PREFERRED_VERSION_udev ?= "141"


#
# meta-moblin package PREFERRED_VERSIONS
#

SRCREV_pn-xf86-video-psb ?= "b6b3bba06fe5a3fe0b1bd6e31a7369dd83812bab"

PREFERRED_VERSION_anerley ?= "0.1.7"
PREFERRED_VERSION_bickley ?= "0.4"
PREFERRED_VERSION_bisho ?= "0.17.1"
PREFERRED_VERSION_bognor-regis ?= "0.5.0"
PREFERRED_VERSION_carrick ?= "1.1.13"
PREFERRED_VERSION_dalston ?= "0.1.12"
PREFERRED_VERSION_gupnp-av ?= "0.4"
PREFERRED_VERSION_hornsey ?= "1.0"
PREFERRED_VERSION_mojito ?= "0.21.7"
PREFERRED_VERSION_nbtk ?= "1.2.3"
PREFERRED_VERSION_moblin-panel-applications ?= "0.1.2"
PREFERRED_VERSION_moblin-panel-media ?= "0.0.7"
PREFERRED_VERSION_moblin-panel-myzone ?= "0.0.12"
PREFERRED_VERSION_moblin-panel-pasteboard ?= "0.0.2"
PREFERRED_VERSION_moblin-panel-people ?= "0.0.9"
PREFERRED_VERSION_moblin-panel-status ?= "0.0.9"
PREFERRED_VERSION_mutter ?= "2.28.1"
PREFERRED_VERSION_mutter-moblin ?= "0.43.8"

