# Known good source dates/revisions/tags to use:
#


#meta-openmoko
SRCREV_pn-dfu-util-native ?= "3139"
SRCREV_pn-dfu-util ?= "3139"
SRCREV_pn-dialer ?= "42a2b4dd62cf94dc905caeb087f5e7e9f418bf93"
SRCREV_pn-gsm0710muxd ?= "6fecc78198dd821bbe29efd096bd8fecd855179d"
SRCREV_pn-gsmd2 ?= "963f34df8fa3ff4b301079dcf86e9acea6b6fe0f"
SRCREV_pn-libmokogsmd2 ?= "4334"
SRCREV_pn-libmokojournal2 ?= "3473"
SRCREV_pn-libmokopanelui2 ?= "3349"
SRCREV_pn-libmokoui2 ?= "4342"
SRCREV_pn-moko-gtk-engine ?= "3612"
SRCREV_pn-openmoko-alsa-scenarios ?= "4406"
SRCREV_pn-openmoko-appearance ?= "3262"
SRCREV_pn-openmoko-appmanager2 ?= "3442"
SRCREV_pn-openmoko-browser2 ?= "4172"
SRCREV_pn-openmoko-calculator2 ?= "3655"
SRCREV_pn-openmoko-common2 ?= "3259"
SRCREV_pn-openmoko-contacts2 ?= "418"
SRCREV_pn-openmoko-dates2 ?= "673"
SRCREV_pn-openmoko-dialer2 ?= "4448"
SRCREV_pn-openmoko-panel-gsm ?= "4335"
SRCREV_pn-openmoko-dialer3 ?= "111"
SRCREV_pn-openmoko-feedreader2 ?= "3645"
SRCREV_pn-openmoko-firststart2 ?= "3158"
SRCREV_pn-openmoko-icon-theme-standard2 ?= "4232"
SRCREV_pn-openmoko-mediaplayer2 ?= "4173"
SRCREV_pn-openmoko-messages2 ?= "4340"
SRCREV_pn-openmoko-sample2 ?= "3537"
SRCREV_pn-openmoko-sound-theme-standard2 ?= "4271"
SRCREV_pn-openmoko-tasks2 ?= "403"
SRCREV_pn-openmoko-terminal2 ?= "4039"
SRCREV_pn-openmoko-theme-standard2 ?= "4338"
SRCREV_pn-openmoko-today2-folders ?= "3704"
SRCREV_pn-openmoko-today2 ?= "4168"
SRCREV_pn-openmoko-worldclock2 ?= "3365"
SRCREV_pn-usbpath-native = "3172"
SRCREV_pn-usbpath = "3172"

#meta-extras
SRCREV_pn-evince ?= "2437"
SRCDATE_maemo-mapper-nohildon ?= "20061114"
SRCREV_pn-libxosd ?= "627"
SRCREV_pn-matchbox-applet-light ?= "1548"
SRCREV_pn-matchbox-common ?= "1561"

# Preferred Versions:
#
PREFERRED_VERSION_libmatchbox ?= "1.9"
PREFERRED_VERSION_gtk-sato-engine ?= "0.3.1"
PREFERRED_VERSION_matchbox-theme-sato ?= "0.1"

PREFERRED_VERSION_glib-2.0 ?= "2.22.3"
PREFERRED_VERSION_glib-2.0-native ?= "2.22.3"
PREFERRED_VERSION_atk ?= "1.24.0"
PREFERRED_VERSION_cairo ?= "1.8.2"
PREFERRED_VERSION_pango ?= "1.22.2"
PREFERRED_VERSION_gtk+ ?= "2.14.2"

PREFERRED_VERSION_dbus ?= "1.2.4"
PREFERRED_VERSION_dbus-native ?= "1.2.4"
PREFERRED_VERSION_dbus-glib ?= "0.82"
PREFERRED_VERSION_dbus-glib-native ?= "0.82"
PREFERRED_VERSION_gnome-vfs ?= "2.22.0"
PREFERRED_VERSION_libgnomecanvas ?= "2.20.0"

PREFERRED_VERSION_evince ?= "2.20.0"
PREFERRED_VERSION_minimo ?= "0.02+cvs${SRCDATE_minimo}"
PREFERRED_VERSION_oprofile ?= "0.9.4"
PREFERRED_VERSION_elfutils ?= "0.89"
PREFERRED_VERSION_hal ?= "0.5.13"
PREFERRED_VERSION_hal-info ?= "20090414"
PREFERRED_VERSION_udev ?= "141"


#
# meta-moblin package PREFERRED_VERSIONS
#

SRCREV_pn-xf86-video-psb ?= "b6b3bba06fe5a3fe0b1bd6e31a7369dd83812bab"

PREFERRED_VERSION_anerley ?= "0.1.7"
PREFERRED_VERSION_bickley ?= "0.4"
PREFERRED_VERSION_bisho ?= "0.17.1"
PREFERRED_VERSION_bognor-regis ?= "0.5.0"
PREFERRED_VERSION_carrick ?= "1.1.13"
PREFERRED_VERSION_dalston ?= "0.1.12"
PREFERRED_VERSION_gupnp-av ?= "0.4"
PREFERRED_VERSION_hornsey ?= "1.0"
PREFERRED_VERSION_mojito ?= "0.21.7"
PREFERRED_VERSION_nbtk ?= "1.2.3"
PREFERRED_VERSION_moblin-panel-applications ?= "0.1.2"
PREFERRED_VERSION_moblin-panel-media ?= "0.0.7"
PREFERRED_VERSION_moblin-panel-myzone ?= "0.0.12"
PREFERRED_VERSION_moblin-panel-pasteboard ?= "0.0.2"
PREFERRED_VERSION_moblin-panel-people ?= "0.0.9"
PREFERRED_VERSION_moblin-panel-status ?= "0.0.9"
PREFERRED_VERSION_mutter ?= "2.28.1"
PREFERRED_VERSION_mutter-moblin ?= "0.43.8"

