#!/bin/sh

usage() {
    echo "$0 <OEINIT> <BUILDDIR>"
    echo "  OEINIT:   path to directory where the .vscode folder is"
    echo "  BUILDDIR: directory passed to the oe-init-setup-env script"
}

if [ "$#" -ne 2 ]; then
    usage
    exit 1
fi

OEINIT=$(readlink -f "$1")
BUILDDIR=$(readlink -f "$2")
VSCODEDIR=$OEINIT/.vscode

if [ ! -d "$OEINIT" ] || [ ! -d "$BUILDDIR" ]; then
    echo "$OEINIT and/or $BUILDDIR directories are not present."
    exit 1
fi

mkdir -p "$VSCODEDIR"
VSCODE_SETTINGS_TMP=$(mktemp -p "$VSCODEDIR")
ws_builddir="$(echo "$BUILDDIR" | sed -e "s|$OEINIT|\${workspaceFolder}|g")"

# poky mode or bitbake-setup mode
ws_build_env="\${workspaceFolder}/oe-init-build-env"
if [ -f "$BUILDDIR/init-build-env" ]; then
    ws_build_env="${ws_builddir}/init-build-env"
fi

bb_dir="$(dirname "$(which bitbake)" | sed 's|/bin$||')"

files_exclude="\"**/_build/**\": true,
        \"**/.git/**\": true,
        \"**/cache/**\": true,
        \"**/downloads/**\": true,
        \"**/node_modules/**\": true,
        \"**/oe-init-build-env-dir/**\": true,
        \"**/oe-scripts/**\": true,
        \"**/sstate-cache/**\": true,
        \"**/workspace/attic/**\": true"

search_exclude="\"**/buildhistory/**\": true,
        \"**/oe-logs/**\": true,
        \"**/oe-workdir/**\": true,
        \"**/tmp*/**\": true,
        \"**/workspace/sources/**\": true"

# If BUILDDIR is in scope of VSCode ensure VSCode does not try to index the build folder.
# This would lead to a busy CPU and finally to an OOM exception.
cat <<EOMsettings > "$VSCODE_SETTINGS_TMP"
{
    "bitbake.pathToBitbakeFolder": "$bb_dir",
    "bitbake.pathToBuildFolder": "$ws_builddir",
    "bitbake.pathToEnvScript": "$ws_build_env",
    "bitbake.workingDirectory": "\${workspaceFolder}",
    "files.exclude": {
        $files_exclude
    },
    "search.exclude": {
        $files_exclude,
        $search_exclude
    },
    "files.watcherExclude": {
        $files_exclude,
        $search_exclude
    },
    "python.analysis.exclude": [
        "**/_build/**",
        "**/.git/**",
        "**/buildhistory/**",
        "**/cache/**",
        "**/downloads/**",
        "**/node_modules/**",
        "**/oe-logs/**",
        "**/oe-workdir/**",
        "**/sstate-cache/**",
        "**/tmp*/**",
        "**/workspace/attic/**",
        "**/workspace/sources/**",
        "**/oe-init-build-env-dir/**",
        "**/oe-scripts/**"
    ]
}
EOMsettings

mv -f "$VSCODE_SETTINGS_TMP" "$VSCODEDIR/settings.json"

# Ask the user if the yocto-bitbake extension should be installed
VSCODE_EXTENSIONS=$VSCODEDIR/extensions.json
cat <<EOMextensions > "$VSCODE_EXTENSIONS"
{
    "recommendations": [
        "yocto-project.yocto-bitbake"
    ]
}
EOMextensions

echo "You had no $VSCODEDIR configuration."
echo "These configuration files have therefore been created for you."
