#!/bin/sh

# Poky Automated Build Server Enviroment Setup Script
#
# Copyright (C) 2006-2007 OpenedHand Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

TARGETDIR=/srv/poky/autobuild-output
CURRDIR=`pwd`
if   [ "$CURRDIR" = "/srv/poky/autobuild/full-shihtzu/build" ]; then
    ABTARGET="poky"
elif [ "$CURRDIR" = "/srv/poky/autobuild/full-bleeding-shihtzu/build" ]; then
    ABTARGET="poky-bleeding"
elif [ "$CURRDIR" = "/srv/poky/autobuild/toolchain-shihtzu/build" ]; then
    ABTARGET="toolchain"
elif [ "$CURRDIR" = "/srv/poky/autobuild/incremental-shihtzu/build" ]; then
    ABTARGET="incremental"
fi

if [ "xpreamble" = "x$1" ]; then
    mkdir -p ./build/tmp/deploy/images 
    rm -f ./build/tmp/deploy/images/images-complete
    svn info > ./build/tmp/deploy/images/svninfo
    exit 0
fi

BDIR="build"
. ./scripts/poky-env-internal
POSTPROCESS=`which poky-autobuild-postprocess`

if [ "xcomplete" = "x$1" ]; then
    touch ./tmp/deploy/images/images-complete
    chmod a+w ./tmp/deploy/images/images-complete
    if [ "x$POSTPROCESS" != "x" ]; then
        cd ..
        $POSTPROCESS $ABTARGET $TARGETDIR
    fi
    exit 0
fi

CONFFILE="./conf/auto.conf"

if [ ! -e "$CONFFILE" ]; then
    if [ ! -d "./conf" ]; then
        mkdir -p "./conf"
    fi
    echo 'PACKAGE_CLASSES = "package_ipk package_deb"' > "$CONFFILE"
    echo 'BB_NUMBER_THREADS = "6"' >> "$CONFFILE"
    echo 'PARALLEL_MAKE = "-j 6"' >> "$CONFFILE"
    echo 'DL_DIR = "/srv/poky/sources"' >> "$CONFFILE"
fi

bitbake $@

retval=$?

if [ "x$POSTPROCESS" != "x" ]; then
    cd ..
    $POSTPROCESS $ABTARGET $TARGETDIR
fi

exit $?
