#!/bin/sh

# Poky Automated Build Server Enviroment Setup Script
#
# Copyright (C) 2006-2007 OpenedHand Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

SRVWORKDIR=/home/buildbot
TARGETDIR=$SRVWORKDIR/autobuild-output
CURRDIR=`pwd`
if   [ "$CURRDIR" = "$SRVWORKDIR/poky/full-shihtzu/build" ]; then
    ABTARGET="poky"
elif [ "$CURRDIR" = "$SRVWORKDIR/poky/full-bleeding-shihtzu/build" ]; then
    ABTARGET="poky-bleeding"
elif [ "$CURRDIR" = "$SRVWORKDIR/poky/toolchain-shihtzu/build" ]; then
    ABTARGET="toolchain"
elif [ "$CURRDIR" = "$SRVWORKDIR/pokky/incremental-shihtzu/build" ]; then
    ABTARGET="incremental"
elif [ "$CURRDIR" = "$SRVWORKDIR/poky/full-darwin-shihtzu/build" ]; then
    ABTARGET="darwin"
    if [ ! -d "$CURRDIR/meta-darwin" ]; then
        svn co http://svn.o-hand.com/repos/poky/branches/experimental/meta-darwin $CURRDIR/meta-darwin
    else
        cd $CURRDIR/meta-darwin
	svn up
	cd $CURRDIR
    fi
fi

if [ "xpreamble" = "x$1" ]; then
    mkdir -p ./build/tmp/deploy/images 
    rm -f ./build/tmp/deploy/images/images-complete
    svn info > ./build/tmp/deploy/images/svninfo
    exit 0
fi

BDIR="build"
. ./scripts/poky-env-internal
BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE"
POSTPROCESS=`which poky-autobuild-postprocess-moblin`

if [ "xcomplete" = "x$1" ]; then
    touch ./tmp/deploy/images/images-complete
    chmod a+w ./tmp/deploy/images/images-complete
    if [ "x$POSTPROCESS" != "x" ]; then
        cd ..
        $POSTPROCESS $ABTARGET $TARGETDIR
    fi
    exit 0
fi

CONFFILE="./conf/auto.conf"

if [ ! -e "$CONFFILE" ]; then
    if [ ! -d "./conf" ]; then
        mkdir -p "./conf"
    fi
    echo 'PACKAGE_CLASSES = "package_ipk package_deb package_rpm"' > "$CONFFILE"
    echo 'BB_NUMBER_THREADS = "6"' >> "$CONFFILE"
    echo 'PARALLEL_MAKE = "-j 6"' >> "$CONFFILE"
    echo "DL_DIR = \"$SRVWORKDIR/sources\"" >> "$CONFFILE"
    echo 'INHERIT += "poky-autobuild-notifier"' >> "$CONFFILE"
    echo 'INHERIT += "poky-moblin-autobuilder-proxy-config"' >> "$CONFFILE"
    if [ "$ABTARGET" = "darwin" ]; then
        echo 'PACKAGE_CLASSES += "package_tar"' >> "$CONFFILE"
	echo "BBFILES += \"$CURRDIR/meta-darwin/packages/*/*.bb\"" >> "./conf/local.conf"
        echo 'POKYMODE = "darwin"' >> "$CONFFILE"
        echo 'DARWINFILES = "file:///srv/poky/sources/"' >> "$CONFFILE"
        echo 'INHERIT_INSANE = ""' >> "$CONFFILE"
        echo "FILESPATH_append = \":$CURRDIR/meta-darwin/files\"" >> "$CONFFILE"
    fi
fi

BBPATH=$SRVWORKDIR/localmeta:$BBPATH

if [ "$ABTARGET" = "darwin" ]; then
    BBPATH=$CURRDIR/meta-darwin:$BBPATH
fi

bitbake $@

retval=$?

if [ "x$POSTPROCESS" != "x" ]; then
    cd ..
    $POSTPROCESS $ABTARGET $TARGETDIR
fi

exit $retval
