#!/bin/sh

# Poky Build Enviroment Setup Script
#
# Copyright (C) 2006-2007 OpenedHand Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


#if test x"$0" = x"./poky-init-build-env"; then
#   echo "Error: Run via '. ./poky-init-build-env'"
#   exit 1
#fi

if [ "xpreamble" = "x$1" ]; then
    mkdir -p ./build/tmp/deploy/images 
    rm -f ./build/tmp/deploy/images/images-complete
    svn info >> ./build/tmp/deploy/images/svninfo
    exit 0
fi

if [ "xcomplete" = "x$1" ]; then
    touch ./build/tmp/deploy/images/images-complete
    chmod a+w ./build/tmp/deploy/images/images-complete
    exit 0
fi

CONFFILE="./build/conf/auto.conf"

if [ ! -e "$CONFFILE" ]; then
    if [ ! -d "./build/conf" ]; then
        mkdir -p "./build/conf"
    fi
    echo 'PACKAGE_CLASSES = "package_ipk package_deb"' > "$CONFFILE"
    echo 'BB_NUMBER_THREADS = "4"' >> "$CONFFILE"
    echo 'PARALLEL_MAKE = "-j 4"' >> "$CONFFILE"
    echo 'DL_DIR = "/srv/poky/sources"' >> "$CONFFILE"
fi

BBTARGET="$1"
shift

. ./scripts/poky-env-internal

bitbake $BBTARGET
