#!/bin/bash

# Handle Poky <-> QEmu interface voodoo
#
# Copyright (C) 2006-2007 OpenedHand Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


if [ "x$BUILDDIR" = "x" ]; then
    echo "You need to source poky-init-build-env before running this script"
    exit 1
fi

INTERNAL_SCRIPT=`which poky-qemu-internal`

if [ "x$1" = "x" ]; then
    echo
    echo "Run as $0 MACHINE IMAGETYPE ZIMAGE IMAGEFILE"
    echo "where:"
    echo "  MACHINE - the machine to emulate (qemuarm, qemux86)"
    echo "  IMAGETYPE - the type of image to run (ext2, nfs) (default: ext2)"
    echo "  ZIMAGE - the kernel to use (optional)"
    echo "  IMAGEFILE - the image file/location to use (optional)"
    exit 1
else
    MACHINE=$1
    shift
fi

if [ "x$1" != "x" ]; then
    TYPE=$1
    shift
else
    TYPE="ext3"
    if [ "$MACHINE" = "akita" ]; then
        TYPE="jffs2"
    fi
    if [ "$MACHINE" = "nokia800" ]; then
        TYPE="jffs2"
    fi
    if [ "$MACHINE" = "spitz" ]; then
        TYPE="ext3"
    fi
fi

if [ "x$1" != "x" ]; then
    ZIMAGE=$1
    shift
fi

if [ "x$1" != "x" ]; then
    HDIMAGE=$1
    shift
fi

if [ "$MACHINE" = "qemuarm" -o "$MACHINE" = "spitz" -o "$MACHINE" = "borzoi" -o "$MACHINE" = "akita" -o "$MACHINE" = "nokia800" ]; then
    if [ "x$ZIMAGE" = "x" ]; then
        ZIMAGE=$BUILDDIR/tmp/deploy/images/zImage-$MACHINE.bin
    fi
    CROSSPATH=$BUILDDIR/tmp/cross/arm-poky-linux-gnueabi/bin
fi

function findimage {
    where=$1
    machine=$2
    extension=$3
    names=$4
    for name in $names;
    do 
	fullname=$where/$name-$machine.$extension
        if [ -e "$fullname" ]; then
            HDIMAGE=$fullname
            return
        fi
    done
    echo "Couldn't find image in $where. Attempted image names were:"
    for name in $names;
    do 
        echo $name-$machine.$extension
    done
    exit 1
}

if [ "$MACHINE" = "qemuarm" ]; then
    if [ "$TYPE" = "ext3" ]; then
        if [ "x$HDIMAGE" = "x" ]; then
            T=$BUILDDIR/tmp/deploy/images
            findimage $T qemuarm ext3 "poky-image-sdk poky-image-sato poky-image-minimal"
        fi
    fi
fi

if [ "$MACHINE" = "spitz" ]; then
    if [ "$TYPE" = "ext3" ]; then
        if [ "x$HDIMAGE" = "x" ]; then
           HDIMAGE=$BUILDDIR/tmp/deploy/images/poky-image-sato-spitz.ext3
        fi
    fi
fi

if [ "$MACHINE" = "akita" ]; then
    if [ "$TYPE" = "jffs2" ]; then
        if [ "x$HDIMAGE" = "x" ]; then
           HDIMAGE=$BUILDDIR/tmp/deploy/images/poky-image-sato-akita.jffs2
        fi
    fi
fi

if [ "$MACHINE" = "nokia800" ]; then
    if [ "$TYPE" = "jffs2" ]; then
        if [ "x$HDIMAGE" = "x" ]; then
           HDIMAGE=$BUILDDIR/tmp/deploy/images/poky-image-sato-nokia800.jffs2
        fi
    fi
fi


if [ "$MACHINE" = "qemux86" ]; then
    if [ "x$ZIMAGE" = "x" ]; then
        ZIMAGE=$BUILDDIR/tmp/deploy/images/bzImage-$MACHINE.bin
    fi
    if [ "$TYPE" = "ext3" ]; then
        if [ "x$HDIMAGE" = "x" ]; then
            T=$BUILDDIR/tmp/deploy/images
            findimage $T qemux86 ext3 "molbin-image-sdk moblin-image-netbook poky-image-sdk poky-image-sato poky-image-minimal"
        fi
    fi
    CROSSPATH=$BUILDDIR/tmp/cross/i586-poky-linux/bin
fi

if [ ! -e $CROSSPATH/cc ]; then
   ln -s $CROSSPATH/gcc $CROSSPATH/cc
fi

CROSSPATH=$BUILDDIR/tmp/staging/$BUILD_SYS/usr/bin:$CROSSPATH:$BUILDDIR/tmp/cross/bin

. $INTERNAL_SCRIPT
