#!/usr/bin/env bash

# Yocto Project compatibility layer tool wrapper
#
# Creates a temprary build directory to run Yocto Project Compatible
# script to avoid a contaminated environment.
#
# Copyright (C) 2017 Intel Corporation
# Released under the MIT license (see COPYING.MIT)

if [ -z "$BUILDDIR" ]; then
	echo "Please source oe-init-build-env before run this script."
	exit 2
fi

# since we are using a temp directory, use the realpath for output
# log option
output_log=''
while getopts o: name
do
	case $name in
	o) output_log=$(realpath "$OPTARG")
	esac
done
shift $(($OPTIND - 1))

# generate a temp directory to run compat layer script
base_dir=$(realpath $BUILDDIR/../)
cd $base_dir

build_dir=$(mktemp -p $base_dir -d -t build-XXXX)

source oe-init-build-env $build_dir
if [[ $output_log != '' ]]; then
	yocto-compat-layer.py -o "$output_log" "$*"
else
	yocto-compat-layer.py "$@"
fi
retcode=$?

rm -rf $build_dir

exit $retcode
