BB_CONF_FRAGMENT_SUMMARY = "Specifies to build recipes with debugging friendly optimization. \
This influences the value of the SELECTED_OPTIMIZATION variable."
BB_CONF_FRAGMENT_DESCRIPTION = "Enables full debug and backtrace capabilities for all programs \
and libraries in the image, by modifying the SELECTED_OPTIMIZATION variable, \
setting it to '-Og ${DEBUG_LEVELFLAG}'."

DEBUG_OPTIMIZE ?= "1"
