BB_CONF_FRAGMENT_SUMMARY = "Use devtool ide-sdk for development and remote debugging."
BB_CONF_FRAGMENT_DESCRIPTION = "\
This configuration enables the use of devtool ide-sdk. \
Example usage: \
  1. bitbake-config-build enable-fragment core/yocto/devtool-ide-sdk \
     bitbake-config-build enable-fragment core/yocto/root-login-with-empty-password \
  2. The recipe (my-recipe in this case) must be in IMAGE_INSTALL. \
  3. Devtool modify --debug-build my-recipe \
  4. devtool ide-sdk my-recipe core-image-full-cmdline --target root@192.168.7.2' \
  5. runqemu snapshot \
  6. code $BUILDDIR/workspace/sources/my-recipe \
  7. Develop and debug the sources of my-recipe from VSCode remotely on the device. \
\
Optimize build time: with devtool ide-sdk the dbg tar is not needed \
(if booting the target via NFS is not used for remote debugging) \
IMAGE_FSTYPES_DEBUGFS = "" \
"

# Build the companion debug file system
IMAGE_GEN_DEBUGFS = "1"

# Without copying the binaries into roofs-dbg, GDB does not find all source files.
IMAGE_CLASSES += "image-combined-dbg"

# Remote debugging needs gdbserver on the target device
IMAGE_INSTALL:append = " gdbserver"
