#!/bin/sh
# Copyright (C) 2016 O.S. Systems Software LTDA.

export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

usage() {
    cat <<EOF
    $0 <openvt arguments> -- <weston options>
EOF
}

if test $# -lt 2; then
	usage
	exit 1
fi

openvt_args=""
while [ -n "$1" ]; do
	openvt_args="$openvt_args $1"
	shift

	if [ "$1" = "--" ]; then
		shift
		break
	fi
done

weston_args=$*

if test -z "$XDG_RUNTIME_DIR"; then
    export XDG_RUNTIME_DIR=/run/user/`id -u`
    mkdir --parents $XDG_RUNTIME_DIR
    chmod 0700 $XDG_RUNTIME_DIR
fi

exec openvt $openvt_args -- weston $weston_args --log=/var/log/weston.log
