#!/bin/sh
# pkgconf wrapper to deal with pkg-config/pkgconf compatibility issues
#
# Copyright (C) 2015 Christopher Larson <chris_larson@mentor.com>
# License: MIT (see COPYING.MIT at the root of the repository for terms)

exec pkgconf "$@"
