Upstream-Status: Inappropriate [configuration]

diff -ruN pciutils-3.1.7-orig/Makefile pciutils-3.1.7/Makefile
--- pciutils-3.1.7-orig/Makefile	2011-07-11 14:41:59.000000000 +0800
+++ pciutils-3.1.7/Makefile	2011-07-11 14:42:31.000000000 +0800
@@ -31,7 +31,7 @@
 IDSDIR=$(SHAREDIR)
 MANDIR:=$(shell if [ -d $(PREFIX)/share/man ] ; then echo $(PREFIX)/share/man ; else echo $(PREFIX)/man ; fi)
 INCDIR=$(PREFIX)/include
-LIBDIR=$(PREFIX)/lib
+LIBDIR=$(libdir)
 PKGCFDIR=$(LIBDIR)/pkgconfig
 
 # Commands
