DESCRIPTION = "GNOME Terminal"
LICENSE = "GPL"
DEPENDS = "gtk+ glib-2.0 startup-notification dbus-glib vte"

inherit gnome

# Remove an autogenerated file that needs to be rebuilt
do_configure_prepend () {
	rm -f ${S}/src/terminal-type-builtins.c
}

